const APP={role:null,user:null,page:"dashboard",group:"小學組",tab:"正式評分",currentId:null};
const LS="animal-lit-award-demo-v2";
const demoWorks=[
{id:"ES-001",group:"小學組",cat:"第一類",title:"牠不是玩具",author:"匿名 001",words:286,periods:12,status:"正式評分",body:"放學回家時，我總是先去看看家裡的狗狗。以前我以為喜歡牠，就是一直抱牠、跟牠玩。後來在課文裡讀到飼主責任，我才知道真正的喜歡，是在牠需要安靜時不打擾，也要每天準備乾淨的水和食物。\n\n動物不是買回家的玩具。當我們決定讓牠成為家人，就要陪牠走完一生。"},
{id:"ES-002",group:"小學組",cat:"第一類",title:"一條牽繩的距離",author:"匿名 002",words:297,periods:17,status:"正式評分",warning:"句號超過15個",body:"公園裡有許多人帶狗散步。我曾經覺得狗狗自由奔跑很快樂，直到老師說明不放養的理由，我才發現牽繩不是限制，而是一種保護。\n\n牽繩可以避免狗狗突然衝向馬路，也能讓怕狗的人安心。對動物負責，有時不是給牠最多自由，而是替牠想得更遠。"},
{id:"ES-003",group:"小學組",cat:"第二類",title:"陪你慢慢變老",author:"匿名 003",words:260,periods:11,status:"正式評分",body:"我家的老狗走路越來越慢。以前我嫌牠散步太慢，現在我會陪牠一步一步走。課堂上提到終生陪伴，我想到牠小時候陪我長大，現在換我陪牠變老。"},
{id:"JH-001",group:"國中組",cat:"第一類",title:"不是喜歡就帶回家",author:"匿名 004",words:482,periods:18,status:"正式評分",body:"「好可愛，好想養。」這句話很容易說出口，但一個生命進入家庭後，責任可能延續十幾年。課文談到不衝動飼養，讓我重新思考喜歡與負責的差別。\n\n真正的飼主責任，是先評估時間、經濟與居住環境，也願意面對生病、老化與生活改變。把動物帶回家之前多想一步，也許正是避免棄養的第一步。"},
{id:"JH-002",group:"國中組",cat:"第一類",title:"名字背後的責任",author:"匿名 005",words:466,periods:21,status:"正式評分",warning:"句號超過20個",body:"替寵物取名字很簡單，但讓這個名字被好好照顧一生並不簡單。登記、絕育、醫療、陪伴，看起來是不同的事情，其實都指向同一件事：我們必須為自己的選擇負責。"},
{id:"SH-001",group:"高中職組",cat:"第一類",title:"當陪伴成為承諾",author:"匿名 006",words:495,periods:19,status:"正式評分",body:"我們常用「家人」稱呼伴侶動物，卻未必願意承擔家人所代表的長期責任。飼主責任不是一句溫柔的口號，而是一連串具體選擇：不傷害、不棄養、不放養、不衝動飼養、登記、絕育，以及終生陪伴。\n\n真正值得被教育的不只是如何愛動物，而是如何對一個依賴我們的生命負責。"},
{id:"ES-X01",group:"小學組",cat:"第一類",title:"超過字數示範件",author:"匿名 X01",words:342,periods:14,status:"剔除",exclude:"字數超過（342 / 300）",body:"此為系統示範資料，正式公開版本不含學生個資。"},
{id:"JH-X01",group:"國中組",cat:"第二類",title:"重複投稿舊件示範",author:"匿名 X02",words:380,periods:17,status:"剔除",exclude:"重複投稿－舊件",linked:"JH-003",body:"此為舊版投稿示範，系統保留紀錄但不進入評審作品池。"},
{id:"JH-P01",group:"國中組",cat:"第一類",title:"同名勾稽待確認",author:"匿名 P01",words:420,periods:18,status:"待確認",warning:"姓名相同；Email/學校/家長資料不完全一致",body:"此件等待管理員判斷是否為同一投稿人。"}
];
const judges=[{id:"j1",name:"林評審",field:"文學",groups:["小學組","國中組","高中職組"]},{id:"j2",name:"陳評審",field:"教育",groups:["小學組","國中組","高中職組"]},{id:"j3",name:"王評審",field:"動保",groups:["小學組","國中組","高中職組"]}];
function seed(){let d=localStorage.getItem(LS);if(!d){let scores={};demoWorks.filter(x=>x.status==="正式評分").forEach((w,i)=>{scores[w.id]={j1:{o:Math.min(20,15+(i*2)%6),b:Math.min(20,16+(i*3)%5),l:Math.min(20,15+(i*4)%6),v:Math.min(40,30+(i*5)%11),note:""},j2:{o:Math.min(20,16+(i*3)%5),b:Math.min(20,15+(i*2)%6),l:Math.min(20,16+(i*4)%5),v:Math.min(40,31+(i*3)%10),note:""},j3:{o:0,b:0,l:0,v:0,note:""}}});d=JSON.stringify({works:demoWorks,scores,submitted:{j1:true,j2:true,j3:false}});localStorage.setItem(LS,d)}return JSON.parse(d)}
let DB=seed(); function save(){localStorage.setItem(LS,JSON.stringify(DB))}
function total(s){return (s?.o||0)+(s?.b||0)+(s?.l||0)+(s?.v||0)}
function getJudgeRanks(jid,group){let a=DB.works.filter(w=>w.status==="正式評分"&&(!group||w.group===group)).map(w=>({id:w.id,score:total(DB.scores[w.id]?.[jid])})).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));let last=null,rank=0;return Object.fromEntries(a.map((x,i)=>{if(x.score!==last)rank=i+1;last=x.score;return[x.id,rank]}))}
function overall(group){let rs=Object.fromEntries(judges.map(j=>[j.id,getJudgeRanks(j.id,group)]));return DB.works.filter(w=>w.status==="正式評分"&&w.group===group).map(w=>{let sum=judges.reduce((n,j)=>n+(rs[j.id][w.id]||999),0);return{w,sum,ranks:Object.fromEntries(judges.map(j=>[j.id,rs[j.id][w.id]]))}}).sort((a,b)=>a.sum-b.sum||a.w.id.localeCompare(b.w.id))}
function el(s){document.getElementById("app").innerHTML=s}
function login(){el(`<div class="login-wrap"><div class="login glass"><section class="login-info"><div class="badge" style="background:rgba(255,255,255,.18);color:white">2026 第五屆</div><h1>關懷動物<br>文學獎評審平台</h1><p style="line-height:1.8;opacity:.9">以文字看見生命，也讓評選更專注、更透明。評審採匿名閱稿、四項指標評分與個人名次排序。</p><div style="margin-top:28px" class="tiny">評分標準｜散文原創性 20%・文句優美性 20%・邏輯通順性 20%・價值啟發性 40%</div></section><section class="login-box"><h2>登入評審平台</h2><p class="muted">公開連結可進入登入頁，實際資料須使用個人帳號驗證。</p><div class="role-grid"><div class="role active" id="rJudge" onclick="pickRole('judge')"><b>✍️ 評審</b><div class="tiny muted">閱稿、評分、查看我的排序</div></div><div class="role" id="rAdmin" onclick="pickRole('admin')"><b>⚙️ 總管理員</b><div class="tiny muted">初篩、進度、個別與總排名</div></div></div><label class="tiny muted">示範帳號</label><input class="input" id="user" value="judge-demo"><label class="tiny muted">示範密碼</label><input class="input" type="password" id="pass" value="2026"><button class="btn primary" style="width:100%;margin-top:5px" onclick="doLogin()">登入</button><div class="callout tiny">這是公開展示版，不含真實學生姓名、電話或 Email。正式版需接安全後端資料庫。</div></section></div></div>`);APP.role="judge"}
function pickRole(r){APP.role=r;document.getElementById("rJudge").classList.toggle("active",r==="judge");document.getElementById("rAdmin").classList.toggle("active",r==="admin");document.getElementById("user").value=r==="admin"?"admin-demo":"judge-demo"}
function doLogin(){APP.user=APP.role==="admin"?{id:"admin",name:"總管理員"}:{id:"j3",name:"王評審"};APP.page="dashboard";render()}
function logout(){APP.user=null;login()}
function shell(content){let nav=APP.role==="admin"?[["dashboard","總覽"],["submissions","作品／初篩"],["judges","評審管理"],["results","成績與總排名"],["awards","得獎名單"],["settings","規則設定"]]:[["dashboard","我的首頁"],["score","開始／繼續評分"],["myrank","我的評分排序"],["guide","評選說明"]];return `<div class="shell"><header class="topbar glass"><div class="brand"><div class="logo">🐾</div><div><h1>2026 第五屆關懷動物文學獎</h1><div class="muted tiny">評審管理平台</div></div></div><div class="toolbar"><span class="badge purple">${APP.user.name}</span><button class="btn" onclick="logout()">登出</button></div></header><div class="layout"><aside class="sidebar glass"><nav class="nav">${nav.map(x=>`<button class="${APP.page===x[0]?"active":""}" onclick="go('${x[0]}')">${x[1]}</button>`).join("")}</nav><div class="callout tiny" style="margin-top:18px">第一類為優先評選參考，不直接加分。</div></aside><main class="main">${content}</main></div></div>`}
function go(p){APP.page=p;render()}
function groupTabs(){return `<div class="tabs">${["小學組","國中組","高中職組"].map(g=>`<button class="tab ${APP.group===g?"active":""}" onclick="APP.group='${g}';render()">${g}</button>`).join("")}</div>`}
function adminDashboard(){let formal=DB.works.filter(w=>w.status==="正式評分").length,pending=DB.works.filter(w=>w.status==="待確認").length,excluded=DB.works.filter(w=>w.status==="剔除").length;let rows=overall(APP.group);return `<section class="hero glass"><div><span class="badge good">評選進行中</span><h2>評審總控台</h2><p>即時掌握初篩、評分進度與名次加總。</p></div><button class="btn primary" onclick="go('results')">查看即時總排名</button></section><div class="cards"><div class="card glass"><div class="muted">投稿總數（示範）</div><div class="metric">${DB.works.length}</div></div><div class="card glass"><div class="muted">正式評分</div><div class="metric">${formal}</div></div><div class="card glass"><div class="muted">待人工確認</div><div class="metric">${pending}</div></div><div class="card glass"><div class="muted">剔除區</div><div class="metric">${excluded}</div></div></div><section class="section glass"><div class="section-head"><h3>評審進度</h3><span class="tiny muted">完成送出後鎖定</span></div>${judges.map(j=>{let assigned=DB.works.filter(w=>w.status==="正式評分").length;let done=DB.works.filter(w=>w.status==="正式評分"&&total(DB.scores[w.id]?.[j.id])>0).length,p=Math.round(done/assigned*100);return`<div class="judge-row"><b>${j.name}</b><div><div class="progress"><span style="width:${p}%"></span></div><div class="tiny muted" style="margin-top:5px">${done}/${assigned} 件</div></div><b>${p}%</b></div>`}).join("")}</section><section class="section glass"><div class="section-head"><h3>${APP.group}｜暫定名次</h3><span class="badge warn">名次加總制</span></div>${groupTabs()}<div class="table-wrap"><table><thead><tr><th>暫定</th><th>作品</th><th>類別</th>${judges.map(j=>`<th>${j.name}</th>`).join("")}<th>名次和</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td><b>${i+1}</b></td><td>${r.w.id}｜${r.w.title}</td><td><span class="badge ${r.w.cat==="第一類"?"good":""}">${r.w.cat}</span></td>${judges.map(j=>`<td>${r.ranks[j.id]}</td>`).join("")}<td><b>${r.sum}</b></td></tr>`).join("")}</tbody></table></div></section>`}
function submissions(){let tabs=["正式評分","待確認","剔除"];let list=DB.works.filter(w=>w.status===APP.tab);return `<section class="hero glass"><div><h2>作品與初篩管理</h2><p>正式評分、待確認與剔除資料完全分區；剔除只改狀態，不刪除紀錄。</p></div><button class="btn primary" onclick="document.getElementById('file').click()">匯入報名表</button><input id="file" type="file" accept=".xlsx,.xls,.csv" hidden onchange="importHint()"></section><section class="section glass"><div class="tabs">${tabs.map(t=>`<button class="tab ${APP.tab===t?"active":""}" onclick="APP.tab='${t}';render()">${t} ${DB.works.filter(w=>w.status===t).length}</button>`).join("")}</div><div class="table-wrap"><table><thead><tr><th>作品編號</th><th>組別</th><th>類別</th><th>作品名稱</th><th>字數</th><th>狀態／原因</th><th></th></tr></thead><tbody>${list.map(w=>`<tr><td><b>${w.id}</b></td><td>${w.group}</td><td><span class="badge ${w.cat==="第一類"?"good":"purple"}">${w.cat}</span></td><td>${w.title}</td><td>${w.words}</td><td>${w.status==="剔除"?`<span class="badge bad">${w.exclude}</span>`:w.status==="待確認"?`<span class="badge warn">${w.warning}</span>`:w.warning?`<span class="badge warn">${w.warning}</span>`:`<span class="badge good">通過</span>`}</td><td><button class="btn" onclick="viewWork('${w.id}')">檢視</button></td></tr>`).join("")}</tbody></table></div></section>`}
function importHint(){alert("展示版已保留匯入入口；為避免公開網站洩露學生個資，瀏覽器端不會把真實報名表上傳至 GitHub。正式版會改由管理員安全上傳到後端資料庫並執行自動初篩。")}
function viewWork(id){let w=DB.works.find(x=>x.id===id);document.body.insertAdjacentHTML("beforeend",`<div class="modal-back" id="modal" onclick="if(event.target===this)this.remove()"><div class="modal glass"><div class="section-head"><div><span class="badge">${w.id}</span> <span class="badge">${w.group}</span> <span class="badge">${w.cat}</span><h2>${w.title}</h2></div><button class="btn" onclick="document.getElementById('modal').remove()">關閉</button></div><p class="essay-body">${w.body}</p>${w.status!=="正式評分"?`<div class="callout">${w.exclude||w.warning}</div>`:""}</div></div>`)}
function judgesPage(){return `<section class="hero glass"><div><h2>評審管理</h2><p>一位評審可指派多組；評審彼此看不到其他人的分數。</p></div><button class="btn primary" onclick="alert('正式版將建立評審帳號並寄送一次性登入連結')">＋ 新增評審</button></section><section class="section glass"><div class="table-wrap"><table><thead><tr><th>評審</th><th>領域</th><th>負責組別</th><th>狀態</th><th>權限</th></tr></thead><tbody>${judges.map(j=>`<tr><td><b>${j.name}</b></td><td>${j.field}</td><td>${j.groups.join("、")}</td><td><span class="badge ${DB.submitted[j.id]?"good":"warn"}">${DB.submitted[j.id]?"已完成送出":"評分中"}</span></td><td>僅自己作品與排序</td></tr>`).join("")}</tbody></table></div></section>`}
function results(){let rows=overall(APP.group);return `<section class="hero glass"><div><span class="badge warn">暫定結果</span><h2>成績與總排名</h2><p>先依各評審分數產生個人名次，再加總所有評審名次；總和越小越前。</p></div><button class="btn" onclick="alert('正式版可匯出 XLSX / CSV')">匯出成績</button></section><section class="section glass">${groupTabs()}<div class="table-wrap"><table><thead><tr><th>總名次</th><th>作品</th><th>類別</th>${judges.map(j=>`<th>${j.name}<br><span class="tiny">分數 / 名次</span></th>`).join("")}<th>名次總和</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td class="${i===0?"rank1":i===1?"rank2":i===2?"rank3":""}">${i+1}</td><td><b>${r.w.id}</b><br>${r.w.title}</td><td><span class="badge ${r.w.cat==="第一類"?"good":""}">${r.w.cat}</span></td>${judges.map(j=>`<td>${total(DB.scores[r.w.id]?.[j.id])} / <b>${r.ranks[j.id]}</b></td>`).join("")}<td><b>${r.sum}</b></td></tr>`).join("")}</tbody></table></div><div class="callout tiny">同一評審分數相同採競賽排名法（1、1、3）；總名次加總同分時，展示版標示同分，正式決勝規則可依主辦單位後續決議設定。第一類只在相同或相近時作優先錄取參考，不自動加分。</div></section>`}
function awards(){let rows=overall(APP.group),slots=[["第一名",1],["第二名",2],["第三名",3],["佳作",15]],idx=0,html="";for(let [name,n] of slots){let got=rows.slice(idx,idx+n);idx+=n;html+=`<section class="section glass"><div class="section-head"><h3>${name} <span class="badge">${n} 名</span></h3><span class="tiny muted">可由管理員調整／從缺／勻用</span></div>${got.length?got.map((r,i)=>`<div class="judge-row"><b>${r.w.id}</b><span>${r.w.title}　<span class="badge ${r.w.cat==="第一類"?"good":""}">${r.w.cat}</span></span><b>${r.sum}</b></div>`).join(""):`<div class="empty">尚無資料</div>`}</section>`}return `<section class="hero glass"><div><h2>得獎名單配置</h2><p>預設每組：第一名1、第二名2、第三名3、佳作15；得依評審共同決議從缺、勻用或不足額。</p></div></section>${groupTabs()}${html}`}
function settings(){return `<section class="hero glass"><div><h2>競賽規則設定</h2><p>依 2026 第五屆關懷動物文學獎簡章建立。</p></div></section><section class="section glass"><div class="kpi-grid"><div class="kpi"><b>小學組</b><div class="metric">300</div><div class="muted tiny">字以內；句號 >15 示警</div></div><div class="kpi"><b>國中組</b><div class="metric">500</div><div class="muted tiny">字以內；句號 >20 示警</div></div><div class="kpi"><b>高中職組</b><div class="metric">500</div><div class="muted tiny">字以內；句號 >20 示警</div></div></div></section><section class="section glass"><h3>評分權重</h3><div class="judge-row"><b>散文原創性</b><div class="progress"><span style="width:20%"></span></div><b>20%</b></div><div class="judge-row"><b>文句優美性</b><div class="progress"><span style="width:20%"></span></div><b>20%</b></div><div class="judge-row"><b>邏輯通順性</b><div class="progress"><span style="width:20%"></span></div><b>20%</b></div><div class="judge-row"><b>價值啟發性</b><div class="progress"><span style="width:40%"></span></div><b>40%</b></div></section><section class="section glass"><h3>資格與初篩規則</h3><p>每名學生限投一件；重複投稿以最新時間版本為有效件，舊件保留於剔除區。姓名相同不得直接剔除，需再勾稽 Email、學校、班級、家長姓名、家長電話等欄位。第一類有具體課文出處，於評審分數相同或相近時優先錄取參考；第二類為無法確認具體課文出處者。</p></section>`}
function judgeDashboard(){let jid=APP.user.id,formal=DB.works.filter(w=>w.status==="正式評分"),done=formal.filter(w=>total(DB.scores[w.id]?.[jid])>0).length,p=Math.round(done/formal.length*100);return `<section class="hero glass"><div><span class="badge good">匿名評審模式</span><h2>${APP.user.name}，您好</h2><p>請專注閱讀作品並依四項標準評分。系統會自動計算總分與您的個人排名。</p></div><button class="btn primary" onclick="go('score')">繼續評分 →</button></section><div class="cards"><div class="card glass"><div class="muted">已完成</div><div class="metric">${done}</div></div><div class="card glass"><div class="muted">待評</div><div class="metric">${formal.length-done}</div></div><div class="card glass"><div class="muted">完成率</div><div class="metric">${p}%</div></div><div class="card glass"><div class="muted">送出狀態</div><div class="metric" style="font-size:20px">${DB.submitted[jid]?"已鎖定":"評分中"}</div></div></div><section class="section glass"><h3>評選提醒</h3><p>第一類為優先評選參考，但不直接加分。評分標準：散文原創性20%、文句優美性20%、邏輯通順性20%、價值啟發性40%。評審只會看到匿名作品編號，不顯示學生姓名與學校。</p></section>`}
function scorePage(){let list=DB.works.filter(w=>w.status==="正式評分"&&w.group===APP.group);if(!APP.currentId||!list.some(w=>w.id===APP.currentId))APP.currentId=list[0]?.id;let w=list.find(x=>x.id===APP.currentId);if(!w)return`<div class="empty">本組目前無正式作品</div>`;let jid=APP.user.id,s=DB.scores[w.id]?.[jid]||{o:0,b:0,l:0,v:0,note:""},idx=list.findIndex(x=>x.id===w.id),locked=DB.submitted[jid];return `<section class="hero glass"><div><h2>沉浸式閱稿</h2><p>作品留在左側，右側評分；輸入即自動儲存。</p></div>${groupTabs()}</section><div class="score-layout"><article class="essay glass"><div><span class="badge">${w.id}</span> <span class="badge ${w.cat==="第一類"?"good":"purple"}">${w.cat}</span> <span class="badge">${w.words} 字</span>${w.warning?` <span class="badge warn">⚠ ${w.warning}</span>`:""}</div><div class="essay-title">${w.title}</div><div class="essay-body">${w.body}</div></article><aside class="score-panel glass"><div class="section-head"><h3>我的評分</h3><span class="tiny muted" id="saved">✓ 已儲存</span></div><div class="criteria">${crit("o","散文原創性",20,s.o,locked)}${crit("b","文句優美性",20,s.b,locked)}${crit("l","邏輯通順性",20,s.l,locked)}${crit("v","價值啟發性",40,s.v,locked)}</div><div class="total"><span>總分</span><strong id="total">${total(s)}</strong><span>/100</span></div><textarea id="note" rows="4" style="width:100%" placeholder="評審私人備註（選填）" ${locked?"disabled":""} oninput="saveScore('${w.id}','note',this.value)">${s.note||""}</textarea><div class="toolbar" style="margin-top:14px"><button class="btn" ${idx===0?"disabled":""} onclick="APP.currentId='${list[Math.max(0,idx-1)].id}';render()">← 上一篇</button><button class="btn primary" ${idx===list.length-1?"disabled":""} onclick="APP.currentId='${list[Math.min(list.length-1,idx+1)].id}';render()">下一篇 →</button></div>${locked?`<div class="callout">本評審結果已送出並鎖定。正式版需由管理員解除後才能修改。</div>`:""}</aside></div>`}
function crit(k,name,max,val,locked){return `<div class="criterion"><div class="criterion-head"><div><b>${name}</b><div class="tiny muted">滿分 ${max}</div></div><input class="input score-input" type="number" min="0" max="${max}" value="${val||0}" ${locked?"disabled":""} oninput="saveScore('${APP.currentId}','${k}',this.value,${max})"></div></div>`}
function saveScore(id,k,v,max){let jid=APP.user.id;if(DB.submitted[jid])return;if(!DB.scores[id])DB.scores[id]={};if(!DB.scores[id][jid])DB.scores[id][jid]={o:0,b:0,l:0,v:0,note:""};if(k==="note")DB.scores[id][jid].note=v;else DB.scores[id][jid][k]=Math.max(0,Math.min(max,Number(v)||0));save();let t=document.getElementById("total");if(t)t.textContent=total(DB.scores[id][jid]);let sv=document.getElementById("saved");if(sv){sv.textContent="✓ 已自動儲存";setTimeout(()=>sv.textContent="✓ 已儲存",700)}}
function myrank(){let r=getJudgeRanks(APP.user.id,APP.group);let list=DB.works.filter(w=>w.status==="正式評分"&&w.group===APP.group).map(w=>({w,score:total(DB.scores[w.id]?.[APP.user.id]),rank:r[w.id]})).sort((a,b)=>a.rank-b.rank||a.w.id.localeCompare(b.w.id));return `<section class="hero glass"><div><h2>我的評分排序</h2><p>只有您與總管理員可以看到此排序；其他評審不可見。</p></div><button class="btn ${DB.submitted[APP.user.id]?"good":"primary"}" onclick="toggleSubmit()">${DB.submitted[APP.user.id]?"✓ 已完成送出":"確認完成本組評審"}</button></section><section class="section glass">${groupTabs()}<div class="table-wrap"><table><thead><tr><th>我的名次</th><th>作品</th><th>類別</th><th>我的分數</th></tr></thead><tbody>${list.map(x=>`<tr><td><b>${x.rank}</b></td><td>${x.w.id}｜${x.w.title}</td><td><span class="badge ${x.w.cat==="第一類"?"good":""}">${x.w.cat}</span></td><td><b>${x.score}</b></td></tr>`).join("")}</tbody></table></div></section>`}
function toggleSubmit(){let jid=APP.user.id;if(DB.submitted[jid]){alert("展示版已鎖定。正式系統需由總管理員解除鎖定。");return}if(confirm("確認完成並送出評審結果？送出後將鎖定評分。")){DB.submitted[jid]=true;save();render()}}
function guide(){return `<section class="hero glass"><div><h2>評選說明</h2><p>2026 第五屆關懷動物文學獎｜評審端摘要</p></div></section><section class="section glass"><h3>徵文主題</h3><p>「最喜歡的動物保護課文」，內容須符合飼主責任精神七項至少其一：不傷害、不棄養、不放養、不衝動飼養、要登記、要絕育、要終生陪伴。</p><h3>評分</h3><p>散文原創性20%、文句優美性20%、邏輯通順性20%、價值啟發性40%。</p><h3>類別</h3><p>第一類有具體課文出處，分數相同或相近時得列為優先錄取參考；第二類無法確認具體課文出處。系統不會直接替第一類加分。</p><h3>獎項</h3><p>各組第一名1位、第二名2位、第三名3位、佳作15位；作品未達標準時，評審委員得共同決議從缺、勻用或不足額錄取。</p></section>`}
function render(){if(!APP.user)return login();let c=APP.role==="admin"?(APP.page==="dashboard"?adminDashboard():APP.page==="submissions"?submissions():APP.page==="judges"?judgesPage():APP.page==="results"?results():APP.page==="awards"?awards():settings()):(APP.page==="dashboard"?judgeDashboard():APP.page==="score"?scorePage():APP.page==="myrank"?myrank():guide());el(shell(c))}
login();