const STORE='animal_award_projects_v4';
const APP={role:null,user:null,page:'projects',projectId:null,group:'小學組'};
const PROJECT_TEMPLATE={
  name:'2026 第五屆關懷動物文學獎',year:'2026',status:'評選中',
  groups:['小學組','國中組','高中職組'],
  limits:{'小學組':300,'國中組':500,'高中職組':500},
  periodWarn:{'小學組':15,'國中組':20,'高中職組':20},
  criteria:[['散文原創性',20],['文句優美性',20],['邏輯通順性',20],['價值啟發性',40]],
  awards:[['第一名',1],['第二名',2],['第三名',3],['佳作',15]],
  members:[
    {name:'總管理員',role:'總管理員',status:'啟用'},
    {name:'工作人員甲',role:'工作人員',status:'啟用'},
    {name:'林評審',role:'評審',groups:['小學組','國中組','高中職組'],status:'啟用'},
    {name:'陳評審',role:'評審',groups:['小學組','國中組','高中職組'],status:'啟用'},
    {name:'王評審',role:'評審',groups:['小學組','國中組','高中職組'],status:'啟用'}
  ],works:[],imports:[],createdAt:new Date().toISOString()
};
function seed(){let d=JSON.parse(localStorage.getItem(STORE)||'null');if(!d){d={projects:[{...PROJECT_TEMPLATE,id:'p2026'}]};localStorage.setItem(STORE,JSON.stringify(d));}return d}
let DB=seed();
function save(){localStorage.setItem(STORE,JSON.stringify(DB))}
function esc(v=''){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function current(){return DB.projects.find(p=>p.id===APP.projectId)||null}
function el(s){document.getElementById('app').innerHTML=s}
function login(){el(`<div class="login-wrap"><div class="login glass"><section class="login-info"><span class="badge" style="background:rgba(255,255,255,.18);color:#fff">競賽專案管理</span><h1>關懷動物<br>文學獎評審平台</h1><p style="line-height:1.8">以「一場競賽＝一個專案」管理作品、評審、工作人員、初篩、評分與結果。</p><div class="callout tiny" style="background:rgba(255,255,255,.14);color:#fff">展示站不保存真實帳密與伺服器資料。正式上線需使用受保護後端登入與資料庫。</div></section><section class="login-box"><h2>系統登入</h2><p class="muted">僅供總管理員、工作人員與評審使用。</p><div class="role-grid"><div class="role active" id="rAdmin" onclick="pickRole('總管理員')"><b>總管理員</b><div class="tiny muted">專案、權限、作品、評審與總排名</div></div><div class="role" id="rStaff" onclick="pickRole('工作人員')"><b>工作人員</b><div class="tiny muted">依授權進行匯入與初篩</div></div><div class="role" id="rJudge" onclick="pickRole('評審')"><b>評審</b><div class="tiny muted">匿名閱稿、評分與個人排序</div></div></div><label class="tiny muted">展示帳號</label><input class="input" id="user" value="admin-demo"><label class="tiny muted">展示密碼</label><input class="input" type="password" id="pass" value="2026"><button class="btn primary" style="width:100%;margin-top:6px" onclick="doLogin()">進入展示系統</button></section></div></div>`);APP.role='總管理員'}
function pickRole(r){APP.role=r;['Admin','Staff','Judge'].forEach(k=>document.getElementById('r'+k)?.classList.remove('active'));document.getElementById(r==='總管理員'?'rAdmin':r==='工作人員'?'rStaff':'rJudge')?.classList.add('active');document.getElementById('user').value=r==='總管理員'?'admin-demo':r==='工作人員'?'staff-demo':'judge-demo'}
function doLogin(){APP.user={name:APP.role,role:APP.role};APP.page='projects';render()}
function logout(){APP.user=null;APP.projectId=null;login()}
function shell(content){const p=current();const isAdmin=APP.role==='總管理員';const nav=p?(APP.role==='評審'?[['judgehome','我的首頁'],['judgeworks','開始／繼續評分'],['myrank','我的評分排序'],['projectinfo','評選說明']]:[['overview','專案總覽'],['import','作品匯入'],['works','作品與初篩'],...(isAdmin?[['members','成員與權限'],['results','成績與總排名'],['settings','專案規則']]:[]) ]):[];return `<div class="shell"><header class="topbar glass"><div class="brand"><div class="logo">🐾</div><div><h1>${p?esc(p.name):'競賽專案管理平台'}</h1><div class="muted tiny">${p?'專案式評審管理':'建立、切換與封存歷屆競賽'}</div></div></div><div class="toolbar">${p?`<button class="btn" onclick="APP.projectId=null;APP.page='projects';render()">切換專案</button>`:''}<span class="badge purple">${esc(APP.role)}</span><button class="btn" onclick="logout()">登出</button></div></header><div class="layout"><aside class="sidebar glass"><nav class="nav"><button class="${APP.page==='projects'?'active':''}" onclick="APP.projectId=null;APP.page='projects';render()">專案管理</button>${nav.map(x=>`<button class="${APP.page===x[0]?'active':''}" onclick="APP.page='${x[0]}';render()">${x[1]}</button>`).join('')}</nav><div class="callout tiny" style="margin-top:18px">不同專案的作品、評審、工作人員與結果應彼此隔離。</div></aside><main class="main">${content}</main></div></div>`}
function projectCards(){let canCreate=APP.role==='總管理員';return shell(`<section class="hero glass"><div><span class="badge good">長期管理模式</span><h2>競賽專案</h2><p>每一屆、每一場競賽建立獨立專案，分別管理資料與權限。</p></div>${canCreate?`<button class="btn primary" onclick="newProject()">＋ 建立新專案</button>`:''}</section><div class="cards" style="grid-template-columns:repeat(3,1fr)">${DB.projects.map(p=>`<div class="card glass"><div class="tiny muted">${esc(p.year||'')}</div><h3 style="margin:8px 0">${esc(p.name)}</h3><div class="tabs"><span class="badge good">${esc(p.status||'')}</span><span class="badge">作品 ${p.works.length}</span><span class="badge purple">成員 ${p.members.length}</span></div><button class="btn primary" onclick="openProject('${p.id}')">進入專案</button></div>`).join('')}</div><section class="section glass"><h3>專案式管理的好處</h3><div class="kpi-grid" style="margin-top:14px"><div class="kpi"><b>資料隔離</b><div class="tiny muted">每一屆作品與評分分開保存，不混用。</div></div><div class="kpi"><b>權限隔離</b><div class="tiny muted">每個專案獨立指定工作人員與評審。</div></div><div class="kpi"><b>規則可複製</b><div class="tiny muted">可複製上一屆設定，再修改字數、評分與獎項。</div></div></div></section>`)}
function newProject(){let name=prompt('請輸入專案名稱，例如：2027 第六屆關懷動物文學獎');if(!name)return;let year=prompt('請輸入年度','2027')||'';let id='p'+Date.now();DB.projects.push({...PROJECT_TEMPLATE,id,name,year,works:[],imports:[],members:[{name:'總管理員',role:'總管理員',status:'啟用'}],createdAt:new Date().toISOString()});save();render()}
function openProject(id){APP.projectId=id;APP.page=APP.role==='評審'?'judgehome':'overview';render()}
function overview(){let p=current();let formal=p.works.filter(w=>w.status==='正式評分').length,pending=p.works.filter(w=>w.status==='待確認').length,excluded=p.works.filter(w=>w.status==='剔除').length;return shell(`<section class="hero glass"><div><span class="badge good">${esc(p.status)}</span><h2>${esc(p.name)}</h2><p>專案資料、成員權限與評審結果皆獨立管理。</p></div><button class="btn primary" onclick="APP.page='import';render()">匯入整份 Excel</button></section><div class="cards"><div class="card glass"><div class="muted">作品總數</div><div class="metric">${p.works.length}</div></div><div class="card glass"><div class="muted">正式評分</div><div class="metric">${formal}</div></div><div class="card glass"><div class="muted">待確認</div><div class="metric">${pending}</div></div><div class="card glass"><div class="muted">剔除區</div><div class="metric">${excluded}</div></div></div><section class="section glass"><div class="section-head"><h3>專案資訊</h3><span class="tiny muted">建立於 ${new Date(p.createdAt).toLocaleString('zh-TW')}</span></div><div class="kpi-grid"><div class="kpi"><b>組別</b><div class="tiny muted">${p.groups.join('、')}</div></div><div class="kpi"><b>評分標準</b><div class="tiny muted">${p.criteria.map(x=>x[0]+' '+x[1]+'%').join('、')}</div></div><div class="kpi"><b>獎項</b><div class="tiny muted">${p.awards.map(x=>x[0]+' '+x[1]+' 位').join('、')}</div></div></div></section>`)}
function importPage(){let p=current();return shell(`<section class="hero glass"><div><span class="badge">Excel 批次匯入</span><h2>作品匯入</h2><p>一次匯入一整場競賽的報名資料，再依專案規則執行初篩。</p></div></section><section class="section glass"><div class="section-head"><h3>上傳報名資料</h3><span class="tiny muted">支援 .xlsx、.xls、.csv</span></div><div class="callout"><b>正式環境：</b>檔案必須上傳至受保護的後端伺服器，由伺服器解析並寫入資料庫。這個公開展示頁只在你的瀏覽器本機解析，不會把檔案上傳到 GitHub。</div><input id="fileInput" class="input" type="file" accept=".xlsx,.xls,.csv" onchange="previewFile(this.files[0])"><div id="importPreview" style="margin-top:14px"><div class="empty">尚未選擇檔案</div></div></section><section class="section glass"><h3>匯入後自動處理</h3><div class="kpi-grid" style="margin-top:14px"><div class="kpi"><b>1. 欄位對應</b><div class="tiny muted">辨識時間戳記、姓名、組別、學校、類別、作品名稱與作品內文等欄位。</div></div><div class="kpi"><b>2. 初篩</b><div class="tiny muted">字數限制、句號示警、重複投稿勾稽、第一類／第二類分類。</div></div><div class="kpi"><b>3. 分流</b><div class="tiny muted">正式評分區、待人工確認區、剔除區。</div></div></div></section>${p.imports.length?`<section class="section glass"><h3>匯入紀錄</h3><div class="table-wrap"><table><thead><tr><th>時間</th><th>檔案</th><th>筆數</th><th>正式</th><th>待確認</th><th>剔除</th></tr></thead><tbody>${p.imports.slice().reverse().map(i=>`<tr><td>${esc(i.at)}</td><td>${esc(i.file)}</td><td>${i.total}</td><td>${i.formal}</td><td>${i.pending}</td><td>${i.excluded}</td></tr>`).join('')}</tbody></table></div></section>`:''}`)}
let pendingImport=null;
async function previewFile(file){if(!file)return;let box=document.getElementById('importPreview');box.innerHTML='<div class="callout">正在解析檔案…</div>';try{let rows=[];if(file.name.toLowerCase().endsWith('.csv')){let text=await file.text();let wb=XLSX.read(text,{type:'string'});rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''})}else{let buf=await file.arrayBuffer();let wb=XLSX.read(buf,{type:'array'});rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''})}pendingImport={file:file.name,rows};let hs=rows[0]?Object.keys(rows[0]):[];box.innerHTML=`<div class="kpi-grid"><div class="kpi"><b>檔案</b><div class="tiny muted">${esc(file.name)}</div></div><div class="kpi"><b>資料筆數</b><div class="metric">${rows.length}</div></div><div class="kpi"><b>欄位數</b><div class="metric">${hs.length}</div></div></div><div class="callout tiny">辨識欄位：${hs.slice(0,12).map(esc).join('、')}${hs.length>12?'…':''}</div><button class="btn primary" onclick="runImport()">確認匯入並執行初篩</button>`}catch(e){box.innerHTML=`<div class="callout">檔案解析失敗：${esc(e.message)}</div>`}}
function txt(row,...keys){for(const k of keys){if(row[k]!==undefined&&String(row[k]).trim()!=='')return String(row[k]).trim()}return ''}
function norm(s){return String(s||'').trim().replace(/臺/g,'台').replace(/\s+/g,'').toLowerCase()}
function countWords(s){return String(s||'').replace(/\s/g,'').length}
function runImport(){if(!pendingImport)return;let p=current();let src=pendingImport.rows.map((r,i)=>{let group=txt(r,'組別');if(/小學|國小/.test(group))group='小學組';else if(/國中/.test(group))group='國中組';else if(/高中|高職|高中職/.test(group))group='高中職組';let body=txt(r,'作品內文');let words=countWords(body);let periods=(body.match(/。/g)||[]).length;let w={id:'W'+Date.now()+'-'+i,order:i+1,submittedAt:txt(r,'時間戳記'),name:txt(r,'學生姓名'),group,school:txt(r,'就讀學校'),className:txt(r,'班級'),category:txt(r,'投稿類別'),publisher:txt(r,'教科書出版社名稱'),subject:txt(r,'科目名稱','科目名稱 2'),title:txt(r,'作品名稱'),body,email:txt(r,'電子郵件地址'),parentName:txt(r,'家長姓名'),parentPhone:txt(r,'家長手機'),parentEmail:txt(r,'家長 E-mail ','家長 E-mail'),studentPhone:txt(r,'學生手機 (如有)'),studentEmail:txt(r,'學生 E-mail (如有)'),words,periods,status:'正式評分',reasons:[],warning:''};let limit=p.limits[group];if(limit&&words>limit){w.status='剔除';w.reasons.push(`字數超過（${words} / ${limit}）`)}let pw=p.periodWarn[group];if(pw&&periods>pw)w.warning=`句號超過 ${pw} 個（共 ${periods} 個）`;return w});
  let byName={};src.forEach(w=>(byName[norm(w.name)]??=[]).push(w));Object.values(byName).forEach(arr=>{if(arr.length<2)return;for(let a=0;a<arr.length;a++)for(let b=a+1;b<arr.length;b++){let x=arr[a],y=arr[b];let score=0,proof=[];[['email','電子郵件'],['parentPhone','家長手機'],['parentEmail','家長電子郵件'],['studentEmail','學生電子郵件']].forEach(([k,n])=>{if(norm(x[k])&&norm(x[k])===norm(y[k])){score+=3;proof.push(n)}});if(norm(x.school)&&norm(x.school)===norm(y.school)){score+=1;proof.push('學校')}if(norm(x.className)&&norm(x.className)===norm(y.className)){score+=1;proof.push('班級')}if(norm(x.parentName)&&norm(x.parentName)===norm(y.parentName)){score+=1;proof.push('家長姓名')}if(score>=4){let dx=Date.parse(x.submittedAt)||0,dy=Date.parse(y.submittedAt)||0;let old=dx<=dy?x:y,newer=dx<=dy?y:x;old.status='剔除';old.reasons.push('重複投稿－舊件');old.linked=newer.id;old.duplicateProof=proof.join('、')}else if(score>=2){[x,y].forEach(w=>{if(w.status==='正式評分'){w.status='待確認';w.reasons.push('疑似重複投稿，需人工確認')}})}}});
  p.works=src;let formal=src.filter(w=>w.status==='正式評分').length,pending=src.filter(w=>w.status==='待確認').length,excluded=src.filter(w=>w.status==='剔除').length;p.imports.push({at:new Date().toLocaleString('zh-TW'),file:pendingImport.file,total:src.length,formal,pending,excluded});pendingImport=null;save();APP.page='works';render();alert(`匯入完成：共 ${src.length} 筆；正式評分 ${formal} 筆、待確認 ${pending} 筆、剔除 ${excluded} 筆。`)}
function worksPage(){let p=current();let tabs=['正式評分','待確認','剔除'];let currentTab=APP.workTab||'正式評分';let list=p.works.filter(w=>w.status===currentTab).sort((a,b)=>p.groups.indexOf(a.group)-p.groups.indexOf(b.group)||(a.category.includes('第一')?-1:1)-(b.category.includes('第一')?-1:1)||a.name.localeCompare(b.name,'zh-Hant'));return shell(`<section class="hero glass"><div><span class="badge">初篩管理</span><h2>作品與初篩</h2><p>正式作品、疑義案件與剔除紀錄分開管理。</p></div><button class="btn primary" onclick="APP.page='import';render()">重新匯入 Excel</button></section><section class="section glass"><div class="tabs">${tabs.map(t=>`<button class="tab ${currentTab===t?'active':''}" onclick="APP.workTab='${t}';render()">${t} ${p.works.filter(w=>w.status===t).length}</button>`).join('')}</div><div class="table-wrap"><table><thead><tr><th>編號</th><th>組別</th><th>類別</th><th>學生姓名</th><th>作品名稱</th><th>字數</th><th>狀態／原因</th></tr></thead><tbody>${list.map((w,i)=>`<tr><td>${i+1}</td><td>${esc(w.group)}</td><td><span class="badge ${w.category.includes('第一')?'good':''}">${esc(w.category)}</span></td><td>${esc(w.name)}</td><td>${esc(w.title)}</td><td>${w.words}</td><td>${w.warning?`<span class="badge warn">${esc(w.warning)}</span>`:''}${w.reasons.map(r=>`<div class="tiny">${esc(r)}</div>`).join('')}</td></tr>`).join('')||`<tr><td colspan="7"><div class="empty">目前沒有資料</div></td></tr>`}</tbody></table></div></section>`)}
function membersPage(){let p=current();return shell(`<section class="hero glass"><div><span class="badge purple">專案權限</span><h2>成員與權限</h2><p>每個專案分別指定總管理員、工作人員與評審。</p></div><button class="btn primary" onclick="addMember()">＋ 新增成員</button></section><section class="section glass"><div class="table-wrap"><table><thead><tr><th>姓名</th><th>角色</th><th>評審組別</th><th>狀態</th></tr></thead><tbody>${p.members.map(m=>`<tr><td>${esc(m.name)}</td><td>${esc(m.role)}</td><td>${esc((m.groups||[]).join('、')||'—')}</td><td><span class="badge good">${esc(m.status)}</span></td></tr>`).join('')}</tbody></table></div></section><section class="section glass"><h3>權限原則</h3><div class="kpi-grid" style="margin-top:14px"><div class="kpi"><b>總管理員</b><div class="tiny muted">專案、成員、個資、初篩、評分、總排名、匯出與稽核。</div></div><div class="kpi"><b>工作人員</b><div class="tiny muted">僅處理被授權的匯入、初篩與行政資料，不可查看完整評審總排名除非另行授權。</div></div><div class="kpi"><b>評審</b><div class="tiny muted">只看分派組別的匿名作品與自己的評分，不接觸投稿者聯絡資訊。</div></div></div></section>`)}
function addMember(){let p=current();let name=prompt('姓名');if(!name)return;let role=prompt('角色：總管理員／工作人員／評審','評審');if(!['總管理員','工作人員','評審'].includes(role))return alert('角色不正確');p.members.push({name,role,status:'啟用',groups:role==='評審'?[...p.groups]:[]});save();render()}
function settingsPage(){let p=current();return shell(`<section class="hero glass"><div><span class="badge">專案規則</span><h2>規則設定</h2><p>建立新專案時可複製上一屆設定，再按新簡章調整。</p></div></section><section class="section glass"><h3>目前規則</h3><div class="kpi-grid" style="margin-top:14px"><div class="kpi"><b>字數限制</b><div class="tiny muted">${Object.entries(p.limits).map(([k,v])=>`${k} ${v} 字`).join('、')}</div></div><div class="kpi"><b>句號示警</b><div class="tiny muted">${Object.entries(p.periodWarn).map(([k,v])=>`${k} 超過 ${v} 個`).join('、')}</div></div><div class="kpi"><b>評分標準</b><div class="tiny muted">${p.criteria.map(x=>`${x[0]} ${x[1]}%`).join('、')}</div></div></div></section>`)}
function simple(title,text){return shell(`<section class="hero glass"><div><h2>${title}</h2><p>${text}</p></div></section><section class="section glass"><div class="empty">此區將依正式後端資料與權限啟用。</div></section>`)}
function render(){if(!APP.user)return login();if(APP.page==='projects'||!APP.projectId)return projectCards();if(APP.page==='overview')return el(overview());if(APP.page==='import')return el(importPage());if(APP.page==='works')return el(worksPage());if(APP.page==='members')return el(membersPage());if(APP.page==='settings')return el(settingsPage());if(APP.page==='results')return el(simple('成績與總排名','依各評審個人名次加總，總和越小名次越前。'));if(APP.page==='judgehome')return el(simple('我的評審專案','只顯示此評審被授權的組別與匿名作品。'));if(APP.page==='judgeworks')return el(simple('匿名閱稿與評分','評審只接觸作品內容與必要評選資訊，不顯示投稿者聯絡個資。'));if(APP.page==='myrank')return el(simple('我的評分排序','完成評分後可查看自己的分數與個人名次排序。'));if(APP.page==='projectinfo')return el(simple('評選說明','評分標準：散文原創性20%、文句優美性20%、邏輯通順性20%、價值啟發性40%。'));}
login();