const 狀態={角色:null,頁面:'首頁',組別:'小學組',匯入資料:[],處理完成:false};
const 示範作品=[
{id:'小-001',組別:'小學組',類別:'第一類',姓名:'匿名001',作品名稱:'牠不是玩具',作品內容:'放學回家時，我總是先去看看家裡的狗狗。以前我以為喜歡牠，就是一直抱牠、跟牠玩。後來在課文裡讀到飼主責任，我才知道真正的喜歡，是在牠需要安靜時不打擾，也要每天準備乾淨的水和食物。',字數:286,句號:12,狀態:'正式評分'},
{id:'小-002',組別:'小學組',類別:'第一類',姓名:'匿名002',作品名稱:'一條牽繩的距離',作品內容:'公園裡有許多人帶狗散步。我曾經覺得狗狗自由奔跑很快樂，直到老師說明不放養的理由，我才發現牽繩不是限制，而是一種保護。',字數:297,句號:17,狀態:'正式評分',示警:'句號數超過 15 個'},
{id:'國-001',組別:'國中組',類別:'第一類',姓名:'匿名003',作品名稱:'不是喜歡就帶回家',作品內容:'「好可愛，好想養。」這句話很容易說出口，但一個生命進入家庭後，責任可能延續十幾年。',字數:482,句號:18,狀態:'正式評分'},
{id:'高-001',組別:'高中職組',類別:'第二類',姓名:'匿名004',作品名稱:'當陪伴成為承諾',作品內容:'我們常用「家人」稱呼伴侶動物，卻未必願意承擔家人所代表的長期責任。',字數:495,句號:19,狀態:'正式評分'},
{id:'剔-001',組別:'小學組',類別:'第一類',姓名:'匿名005',作品名稱:'超過字數示範件',作品內容:'展示資料',字數:342,句號:14,狀態:'剔除',剔除原因:'字數超過（342／300）'},
{id:'待-001',組別:'國中組',類別:'第一類',姓名:'匿名006',作品名稱:'同名勾稽待確認',作品內容:'展示資料',字數:420,句號:18,狀態:'待確認',示警:'同名但其他身分欄位不一致，需人工確認'}
];
let 作品=[...示範作品];
const 評審=[{id:'評審甲',姓名:'林評審'},{id:'評審乙',姓名:'陳評審'},{id:'評審丙',姓名:'王評審'}];
const 評分={};
function 文字長度(t){return String(t||'').replace(/\s/g,'').length}
function 句號數(t){return (String(t||'').match(/。/g)||[]).length}
function 欄位值(r,候選){for(const k of 候選){if(r[k]!==undefined&&String(r[k]).trim()!=='')return String(r[k]).trim()}return ''}
function 正規化(s){return String(s||'').trim().replace(/臺/g,'台').replace(/\s+/g,'').toLowerCase()}
function 同一人分數(a,b){let 分=0;const 比對=[['姓名',4],['電子郵件',4],['家長手機',4],['家長電子郵件',4],['學校',2],['班級',2],['家長姓名',2],['學生手機',3],['學生電子郵件',3]];for(const [k,w] of 比對){if(a[k]&&b[k]&&正規化(a[k])===正規化(b[k]))分+=w}return 分}
function 前處理(rows){const data=rows.map((r,i)=>{const 內容=欄位值(r,['作品內文','作品內容','文章內容','內文']);const 組=欄位值(r,['組別','資格分組','學生組別']);const 類=欄位值(r,['投稿類別','類別']);return {id:'匯-'+String(i+1).padStart(4,'0'),投稿時間:欄位值(r,['時間戳記','投稿時間','填答時間']),姓名:欄位值(r,['學生姓名','姓名']),電子郵件:欄位值(r,['電子郵件地址','電子郵件','Email']),學校:欄位值(r,['就讀學校','學校']),班級:欄位值(r,['班級']),家長姓名:欄位值(r,['家長姓名']),家長手機:欄位值(r,['家長手機','家長聯絡電話']),家長電子郵件:欄位值(r,['家長Email','家長電子郵件']),學生手機:欄位值(r,['學生手機']),學生電子郵件:欄位值(r,['學生Email','學生電子郵件']),組別:組.includes('小')?'小學組':組.includes('國')?'國中組':組.includes('高')?'高中職組':組,類別:類.includes('第一')?'第一類':類.includes('第二')?'第二類':類,作品名稱:欄位值(r,['作品名稱','題目','作品題目']),作品內容:內容,字數:文字長度(內容),句號:句號數(內容),狀態:'正式評分',示警:'',剔除原因:''}});
for(const x of data){const 上限=x.組別==='小學組'?300:500;if(x.字數>上限){x.狀態='剔除';x.剔除原因=`字數超過（${x.字數}／${上限}）`}else if((x.組別==='小學組'&&x.句號>15)||((x.組別==='國中組'||x.組別==='高中職組')&&x.句號>20)){x.示警=`句號數量異常（${x.句號} 個）`}}
for(let i=0;i<data.length;i++){for(let j=i+1;j<data.length;j++){if(!data[i].姓名||正規化(data[i].姓名)!==正規化(data[j].姓名))continue;const 分=同一人分數(data[i],data[j]);if(分>=10){const ai=Date.parse(data[i].投稿時間)||i,aj=Date.parse(data[j].投稿時間)||j;const 舊=ai<=aj?data[i]:data[j],新=ai<=aj?data[j]:data[i];舊.狀態='剔除';舊.剔除原因=`重複投稿－舊件；保留較新投稿 ${新.id}`}else{for(const x of [data[i],data[j]]){if(x.狀態==='正式評分'){x.狀態='待確認';x.示警='姓名相同，但其他勾稽欄位不足以確認為同一人'}}}}}
return data.sort((a,b)=>{const g={'小學組':1,'國中組':2,'高中職組':3},c={'第一類':1,'第二類':2};return (g[a.組別]||9)-(g[b.組別]||9)||(c[a.類別]||9)-(c[b.類別]||9)||a.姓名.localeCompare(b.姓名,'zh-Hant')})}
function CSV解析(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const parseLine=line=>{const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===','&&!q){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out};const head=parseLine(lines[0]);return lines.slice(1).map(l=>{const vals=parseLine(l),o={};head.forEach((h,i)=>o[h.trim()]=vals[i]||'');return o})}
function 上傳檔案(input){const f=input.files?.[0];if(!f)return;document.getElementById('檔名').textContent=f.name;if(/\.csv$/i.test(f.name)){const reader=new FileReader();reader.onload=e=>{狀態.匯入資料=CSV解析(e.target.result);document.getElementById('匯入提示').innerHTML=`已讀取 <b>${狀態.匯入資料.length}</b> 筆資料，可執行初篩。`;document.getElementById('執行按鈕').disabled=false};reader.readAsText(f,'utf-8')}else{狀態.匯入資料=[];document.getElementById('匯入提示').innerHTML='此公開展示環境不會解析真實 Excel 檔。正式版將由受保護的伺服器端解析 XLSX，避免個資停留在公開前端程式。';document.getElementById('執行按鈕').disabled=true}}
function 執行初篩(){if(!狀態.匯入資料.length)return;作品=前處理(狀態.匯入資料);狀態.處理完成=true;狀態.頁面='作品管理';渲染()}
function 版面(內容){const 導覽=狀態.角色==='總管理員'?['首頁','作品匯入','作品管理','評審管理','總排名','資安控管']:狀態.角色==='工作人員'?['首頁','作品匯入','作品管理']:['首頁','評分作業','我的排名','評選說明'];return `<div class="shell"><header class="topbar glass"><div class="brand"><div class="logo">🐾</div><div><h1>2026 第五屆關懷動物文學獎</h1><div class="muted tiny">評審管理平台｜展示環境</div></div></div><div class="toolbar"><span class="badge purple">${狀態.角色}</span><button class="btn" onclick="登出()">登出</button></div></header><div class="layout"><aside class="sidebar glass"><nav class="nav">${導覽.map(x=>`<button class="${狀態.頁面===x?'active':''}" onclick="切換('${x}')">${x}</button>`).join('')}</nav><div class="callout tiny" style="margin-top:18px">展示環境僅使用匿名或本機載入資料，不得放入真實個資。</div></aside><main class="main">${內容}</main></div></div>`}
function 登入頁(){document.getElementById('app').innerHTML=`<div class="login-wrap"><div class="login glass"><section class="login-info"><div class="badge" style="background:rgba(255,255,255,.18);color:white">2026 第五屆</div><h1>關懷動物<br>文學獎評審平台</h1><p style="line-height:1.8;opacity:.9">正式環境僅限總管理員、授權工作人員及受邀評審登入。公開網址只提供登入入口，不公開任何投稿內容與個人資料。</p><div class="tiny" style="margin-top:24px">散文原創性 20%・文句優美性 20%・邏輯通順性 20%・價值啟發性 40%</div></section><section class="login-box"><h2>展示環境</h2><p class="muted">請選擇角色查看系統流程。此處不是正式登入驗證。</p><div class="role-grid"><div class="role" onclick="進入展示('總管理員')"><b>總管理員</b><div class="tiny muted">完整管理與總排名</div></div><div class="role" onclick="進入展示('工作人員')"><b>工作人員</b><div class="tiny muted">依授權處理匯入與初篩</div></div><div class="role" onclick="進入展示('評審')"><b>評審</b><div class="tiny muted">匿名閱稿與自己的排序</div></div></div><div class="callout tiny">正式版禁止在公開原始碼、本機儲存區、網址參數或公開雲端檔案中保存密碼、電話、電子郵件、家長資料與完整投稿名冊。</div></section></div></div>`}
function 進入展示(r){狀態.角色=r;狀態.頁面='首頁';渲染()}function 登出(){狀態.角色=null;登入頁()}function 切換(p){狀態.頁面=p;渲染()}
function 組別頁籤(){return `<div class="tabs">${['小學組','國中組','高中職組'].map(g=>`<button class="tab ${狀態.組別===g?'active':''}" onclick="狀態.組別='${g}';渲染()">${g}</button>`).join('')}</div>`}
function 首頁(){const 正式=作品.filter(x=>x.狀態==='正式評分').length,待=作品.filter(x=>x.狀態==='待確認').length,剔=作品.filter(x=>x.狀態==='剔除').length;if(狀態.角色==='評審')return `<section class="hero glass"><div><span class="badge good">匿名評審</span><h2>評審工作臺</h2><p>只顯示被指派作品與自己的評分資料。</p></div><button class="btn primary" onclick="切換('評分作業')">開始評分</button></section>`;return `<section class="hero glass"><div><span class="badge good">權限控管中</span><h2>${狀態.角色==='總管理員'?'總管理控制臺':'工作人員作業臺'}</h2><p>投稿匯入後先執行初篩，再由管理端確認正式作品池。</p></div><button class="btn primary" onclick="切換('作品匯入')">匯入作品</button></section><div class="cards"><div class="card glass"><div class="muted">全部作品</div><div class="metric">${作品.length}</div></div><div class="card glass"><div class="muted">正式評分</div><div class="metric">${正式}</div></div><div class="card glass"><div class="muted">待確認</div><div class="metric">${待}</div></div><div class="card glass"><div class="muted">剔除區</div><div class="metric">${剔}</div></div></div>`}
function 作品匯入(){return `<section class="hero glass"><div><span class="badge purple">第一步</span><h2>匯入所有投稿作品</h2><p>上傳報名表後，系統依規則建立正式評分、待確認與剔除三個區域。</p></div></section><section class="section glass"><div class="upload-zone"><div style="font-size:42px">📄</div><h3>選擇報名表檔案</h3><p class="muted">正式版支援 XLSX／CSV。公開展示環境僅允許 CSV 於瀏覽器本機測試，不會上傳到伺服器。</p><input id="檔案" type="file" accept=".xlsx,.xls,.csv" onchange="上傳檔案(this)"><p id="檔名" class="tiny muted">尚未選擇檔案</p><div id="匯入提示" class="callout tiny">建議正式匯入前先備份原始報名表。</div><button id="執行按鈕" class="btn primary" disabled onclick="執行初篩()">執行自動初篩</button></div></section><section class="section glass"><h3>自動處理規則</h3><div class="cards"><div class="card"><b>重複投稿</b><p class="tiny muted">同姓名先列候選，再以電子郵件、家長電話、家長電子郵件、學校、班級等多重欄位勾稽。高度確認同一人時保留最新件。</p></div><div class="card"><b>字數限制</b><p class="tiny muted">小學 300 字；國中、高中職 500 字。超過者移入剔除區並保留原因。</p></div><div class="card"><b>句號示警</b><p class="tiny muted">小學超過 15 個；國中、高中職超過 20 個，只示警、不自動剔除。</p></div><div class="card"><b>排序</b><p class="tiny muted">各組第一類優先、第二類其次，再依姓名排序。</p></div></div></section>`}
function 作品管理(){return `${組別頁籤()}${['正式評分','待確認','剔除'].map(s=>`<section class="section glass"><div class="section-head"><h3>${s==='剔除'?'剔除區':s}</h3><span class="tiny muted">${s==='剔除'?'保留紀錄，不提供評審':' '}</span></div><div class="table-wrap"><table><thead><tr><th>編號</th><th>姓名／匿名</th><th>作品名稱</th><th>類別</th><th>字數</th><th>句號</th><th>狀態／原因</th></tr></thead><tbody>${作品.filter(x=>x.組別===狀態.組別&&x.狀態===s).map(x=>`<tr><td>${x.id}</td><td>${狀態.角色==='總管理員'||狀態.角色==='工作人員'?x.姓名:'匿名'}</td><td>${x.作品名稱}</td><td>${x.類別}</td><td>${x.字數}</td><td>${x.句號}</td><td>${x.剔除原因||x.示警||'通過'}</td></tr>`).join('')||'<tr><td colspan="7" class="muted">目前沒有資料</td></tr>'}</tbody></table></div></section>`).join('')}`}
function 評分作業(){return `${組別頁籤()}<section class="section glass"><h3>匿名評分作品</h3><p class="muted">正式版只會載入此評審被指派且通過初篩的作品，不提供學生姓名、學校、電話、電子郵件或家長資料。</p><div class="table-wrap"><table><thead><tr><th>作品編號</th><th>作品名稱</th><th>類別</th><th>狀態</th></tr></thead><tbody>${作品.filter(x=>x.組別===狀態.組別&&x.狀態==='正式評分').map(x=>`<tr><td>${x.id}</td><td>${x.作品名稱}</td><td>${x.類別}</td><td>${x.示警?'<span class="badge warn">管理端已標記</span>':'<span class="badge good">可評分</span>'}</td></tr>`).join('')}</tbody></table></div></section>`}
function 我的排名(){return `<section class="section glass"><h3>我的評分排序</h3><p class="muted">僅顯示自己的評分與個人名次，不顯示其他評審分數。</p></section>`}
function 評審管理(){return `<section class="section glass"><div class="section-head"><h3>評審與工作人員權限</h3><button class="btn primary">新增受邀帳號</button></div><div class="table-wrap"><table><thead><tr><th>角色</th><th>可查看資料</th><th>禁止事項</th></tr></thead><tbody><tr><td>總管理員</td><td>完整管理資料、個別評審分數、總排名、操作紀錄</td><td>不得共用帳號</td></tr><tr><td>工作人員</td><td>依授權處理投稿、初篩、匯入</td><td>預設不得查看總排名、修改評審分數</td></tr><tr><td>評審</td><td>被指派的匿名作品、自己的評分與排序</td><td>不得取得投稿者個資、其他評審分數</td></tr></tbody></table></div></section>`}
function 總排名頁(){return `<section class="section glass"><h3>總排名</h3><p class="muted">正式版依各評審個人名次加總，名次和越小越前；只有總管理員可以查看所有個別評審名次與總排名。</p></section>`}
function 資安控管(){return `<section class="hero glass"><div><span class="badge bad">正式環境必要條件</span><h2>資料安全與權限控管</h2><p>真實投稿資料不得部署於公開 GitHub Pages。</p></div></section><section class="section glass"><div class="cards"><div class="card"><b>伺服器端驗證</b><p class="tiny muted">帳號密碼雜湊、登入工作階段、逾時登出、多因素驗證可選。</p></div><div class="card"><b>角色權限</b><p class="tiny muted">每一支後端介面都重新驗證角色，不只隱藏前端按鈕。</p></div><div class="card"><b>資料最小化</b><p class="tiny muted">評審僅取得匿名作品資料；個資僅授權人員依業務需要存取。</p></div><div class="card"><b>完整稽核</b><p class="tiny muted">登入、匯入、初篩判定、分數修改、解除鎖定、匯出都留下不可任意刪除的紀錄。</p></div></div><div class="callout tiny">建議正式站使用 HTTPS、受保護資料庫、每日備份、資料庫加密、嚴格內容安全政策、登入速率限制、異常登入通知、最小權限帳號及定期權限檢查。</div></section>`}
function 渲染(){if(!狀態.角色){登入頁();return}let c='';if(狀態.頁面==='首頁')c=首頁();else if(狀態.頁面==='作品匯入')c=作品匯入();else if(狀態.頁面==='作品管理')c=作品管理();else if(狀態.頁面==='評分作業')c=評分作業();else if(狀態.頁面==='我的排名')c=我的排名();else if(狀態.頁面==='評審管理')c=評審管理();else if(狀態.頁面==='總排名')c=總排名頁();else if(狀態.頁面==='資安控管')c=資安控管();else c=`<section class="section glass"><h3>${狀態.頁面}</h3><p class="muted">此功能將接續整合至正式後端。</p></section>`;document.getElementById('app').innerHTML=版面(c)}
登入頁();