'use strict';
(function(){
  const SUPABASE_URL='https://ppdrsoltvqiqnbnlimbb.supabase.co';
  const SUPABASE_KEY='sb_publishable_Ev2C5000djbQq4wLDUKh9A_oF3H3WBd';
  const DASHBOARD_VERSION='20260908e';
  const app=document.getElementById('app');
  let sb=null;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function html(body){app.innerHTML=`<main class="login"><div class="login-card">${body}</div></main>`}
  function fail(title,detail){html(`<div class="badge">系統啟動檢查</div><h1>${esc(title)}</h1><p class="muted">${esc(detail)}</p><button class="btn primary" id="retry" style="width:100%;margin-top:16px">重新載入</button>`);document.getElementById('retry').onclick=()=>location.reload()}
  function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.async=true;s.onload=resolve;s.onerror=()=>reject(new Error(src));document.head.appendChild(s)})}
  function dashboardUrl(extra=''){const q=new URLSearchParams();q.set('v',DASHBOARD_VERSION);const incoming=new URLSearchParams(location.search);if(incoming.get('invite'))q.set('invite',incoming.get('invite'));if(extra)q.set('invite',extra);return `./dashboard.html?${q.toString()}${location.hash||''}`}
  async function ensureSDK(){if(window.supabase?.createClient)return true;const sources=['https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.min.js','https://unpkg.com/@supabase/supabase-js@2/dist/umd/supabase.js'];for(const src of sources){try{await Promise.race([loadScript(src),new Promise((_,r)=>setTimeout(()=>r(new Error('timeout')),10000))]);if(window.supabase?.createClient)return true}catch(e){}}return false}
  async function session(){const {data}=await sb.auth.getSession();return data.session||null}
  function login(msg=''){
    const invite=new URLSearchParams(location.search).get('invite');
    html(`<div class="badge">受保護正式系統</div><h1>競賽專案評審管理平台</h1><p class="muted">僅限經授權的管理員、工作人員與評審登入。</p>${msg?`<div class="danger-note">${esc(msg)}</div>`:''}${invite?'<div class="note">你正在使用專案邀請連結，請以受邀電子郵件登入。</div>':''}<form id="loginForm"><label class="label">電子郵件</label><input class="input" name="email" type="email" autocomplete="username" required><label class="label">密碼</label><input class="input" name="password" type="password" autocomplete="current-password" required><button class="btn primary" style="width:100%;margin-top:15px">登入</button></form><button id="setup" class="btn" style="width:100%;margin-top:10px">首次初始化總管理員</button>${invite?'<button id="register" class="btn" style="width:100%;margin-top:10px">尚無帳號，建立受邀帳號</button>':''}`);
    document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await sb.auth.signInWithPassword({email:String(f.get('email')).trim().toLowerCase(),password:String(f.get('password'))});if(error)return login('登入失敗，請確認帳號與密碼。');location.href=dashboardUrl()};
    document.getElementById('setup').onclick=()=>setup();const r=document.getElementById('register');if(r)r.onclick=()=>registerInvite(invite);
  }
  async function setup(){const ses=await session();html(`<div class="badge">首次啟用</div><h1>建立平台總管理員</h1><p class="muted">此流程只能成功一次；驗證碼使用後立即失效。</p>${ses?`<div class="note">目前登入：${esc(ses.user.email)}</div>`:''}<form id="setupForm">${ses?'':`<label class="label">顯示名稱</label><input class="input" name="name" required><label class="label">電子郵件</label><input class="input" name="email" type="email" required><label class="label">設定密碼</label><input class="input" name="password" type="password" minlength="12" maxlength="128" required>`}<label class="label">一次性初始化驗證碼</label><input class="input" name="code" type="password" required autocomplete="off"><button class="btn primary" style="width:100%;margin-top:15px">${ses?'完成總管理員啟用':'建立帳號並啟用'}</button></form><div id="msg"></div><button id="back" class="btn" style="width:100%;margin-top:10px">返回登入</button>`);document.getElementById('back').onclick=()=>login();document.getElementById('setupForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),msg=document.getElementById('msg');let current=await session();let display='';if(!current){display=String(f.get('name')).trim();const email=String(f.get('email')).trim().toLowerCase(),password=String(f.get('password'));const redirect=`${location.origin}${location.pathname}`;const {data,error}=await sb.auth.signUp({email,password,options:{data:{display_name:display},emailRedirectTo:redirect}});if(error){msg.innerHTML=`<div class="danger-note">${esc(error.message)}</div>`;return}if(!data.session){msg.innerHTML='<div class="note">帳號已建立。請先到電子郵件完成驗證，再回到此頁按「首次初始化總管理員」。</div>';return}current=data.session}else display=current.user.user_metadata?.display_name||current.user.email||'';const raw=String(f.get('code'));const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw));const secret_hash=Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('');const res=await fetch(`${SUPABASE_URL}/functions/v1/claim-platform-admin`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${current.access_token}`,'apikey':SUPABASE_KEY},body:JSON.stringify({secret_hash,display_name:display})});const out=await res.json().catch(()=>({}));if(!res.ok){msg.innerHTML=`<div class="danger-note">${esc(out.error||'總管理員啟用失敗。')}</div>`;return}msg.innerHTML='<div class="note">平台總管理員已啟用，正在進入管理後台…</div>';setTimeout(()=>location.href=dashboardUrl(),500)}}
  function registerInvite(token){html(`<div class="badge">受邀成員啟用</div><h1>建立個人帳號</h1><form id="reg"><label class="label">姓名</label><input class="input" name="name" required><label class="label">受邀電子郵件</label><input class="input" name="email" type="email" required><label class="label">設定密碼</label><input class="input" name="password" type="password" minlength="12" maxlength="128" required><button class="btn primary" style="width:100%;margin-top:15px">建立帳號</button></form><div id="msg"></div><button id="back" class="btn" style="width:100%;margin-top:10px">返回登入</button>`);document.getElementById('back').onclick=()=>login();document.getElementById('reg').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),msg=document.getElementById('msg');const redirect=`${location.origin}${location.pathname}?invite=${encodeURIComponent(token||'')}`;const {data,error}=await sb.auth.signUp({email:String(f.get('email')).trim().toLowerCase(),password:String(f.get('password')),options:{data:{display_name:String(f.get('name')).trim()},emailRedirectTo:redirect}});if(error){msg.innerHTML=`<div class="danger-note">${esc(error.message)}</div>`;return}if(!data.session){msg.innerHTML='<div class="note">帳號已建立。請完成電子郵件驗證後，再從原邀請連結登入。</div>';return}location.href=dashboardUrl(token||'')}}
  async function start(){html('<div class="badge">安全連線</div><h1>系統啟動中</h1><p class="muted">正在建立安全連線，通常只需要數秒。</p>');if(!(await ensureSDK()))return fail('系統元件載入失敗','兩個備援來源皆無法載入。請確認網路後重新載入。');try{sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,storage:window.sessionStorage,autoRefreshToken:true,detectSessionInUrl:true}});const ses=await Promise.race([session(),new Promise((_,r)=>setTimeout(()=>r(new Error('timeout')),12000))]);if(ses)location.href=dashboardUrl();else login()}catch(e){fail('安全連線建立失敗','無法連線至身分驗證服務，請重新載入。')}}
  start();
})();