'use strict';
(function(){
 const U='https://ppdrsoltvqiqnbnlimbb.supabase.co',K='sb_publishable_Ev2C5000djbQq4wLDUKh9A_oF3H3WBd',V='20260910g',app=document.getElementById('app');let sb;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const invite=()=>new URLSearchParams(location.search).get('invite')||'';
 const html=b=>app.innerHTML=`<main class="login"><div class="login-card">${b}</div></main>`;
 const showLoading=()=>app.innerHTML='<div class="loader-screen" role="status" aria-live="polite"><div class="loader-center"><div class="loader-book" aria-hidden="true">📖</div><div class="loader-dots" aria-hidden="true"><i></i><i></i><i></i></div><span class="sr-only">載入中</span></div></div>';
 const dash=pid=>`./dashboard.html?v=${V}${pid?`#project/${encodeURIComponent(pid)}`:''}`;
 async function loadSDK(){if(window.supabase?.createClient)return true;for(const src of ['https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.115.0/dist/umd/supabase.min.js','https://unpkg.com/@supabase/supabase-js@2.115.0/dist/umd/supabase.js']){try{await new Promise((ok,no)=>{const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=no;document.head.appendChild(s)});if(window.supabase?.createClient)return true}catch{}}return false}
 async function accept(token){const {data:{session}}=await sb.auth.getSession();if(!session)throw new Error('尚未登入');const r=await fetch(`${U}/functions/v1/accept-project-invitation`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`,apikey:K},body:JSON.stringify({token})});const o=await r.json().catch(()=>({}));if(!r.ok)throw new Error(o.error||'接受邀請失敗');return o.project_id}
 function login(msg=''){
  const t=invite();html(`<div class="badge">${t?'專案邀請':'受保護正式系統'}</div><h1>${t?'加入競賽專案':'競賽專案評審管理平台'}</h1><p class="muted">${t?'如果你是第一次使用，不需要原本就有密碼，請按下方「第一次使用，設定我的密碼」。':'僅限經授權的管理員、工作人員與評審登入。'}</p>${msg?`<div class="danger-note">${esc(msg)}</div>`:''}<form id="login"><label class="label">電子郵件</label><input class="input" name="email" type="email" autocomplete="username" required><label class="label">密碼</label><input class="input" name="password" type="password" autocomplete="current-password" required><button class="btn primary" style="width:100%;margin-top:15px">${t?'已有帳號，登入並接受邀請':'登入'}</button></form>${t?'<button id="new" class="btn" style="width:100%;margin-top:10px">第一次使用，設定我的密碼</button>':'<button id="setup" class="btn" style="width:100%;margin-top:10px">首次初始化總管理員</button>'}`);
  document.getElementById('login').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),email=String(f.get('email')).trim().toLowerCase(),password=String(f.get('password'));const {error}=await sb.auth.signInWithPassword({email,password});if(error)return login('登入失敗。如果你從未設定過密碼，請按「第一次使用，設定我的密碼」。');showLoading();try{const pid=t?await accept(t):'';location.href=dash(pid)}catch(err){login(err.message)}};
  if(t)document.getElementById('new').onclick=()=>register(t);else document.getElementById('setup').onclick=()=>setup();
 }
 function register(t){html(`<div class="badge">受邀成員首次啟用</div><h1>設定你的登入密碼</h1><p class="muted">管理員只指定你的 Email 與權限，不會替你設定或看到密碼。請在這裡自行建立密碼；完成後會直接加入受邀專案，不需要另外點 Email 驗證信。</p><form id="reg"><label class="label">姓名</label><input class="input" name="name" required><label class="label">受邀電子郵件</label><input class="input" name="email" type="email" required><label class="label">設定密碼</label><input class="input" name="password" type="password" minlength="12" maxlength="128" required autocomplete="new-password"><label class="label">再次輸入密碼</label><input class="input" name="password2" type="password" minlength="12" maxlength="128" required autocomplete="new-password"><button class="btn primary" style="width:100%;margin-top:15px">設定密碼並加入專案</button></form><div id="msg"></div><button id="back" class="btn" style="width:100%;margin-top:10px">返回</button>`);document.getElementById('back').onclick=()=>login();document.getElementById('reg').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),msg=document.getElementById('msg'),email=String(f.get('email')).trim().toLowerCase(),password=String(f.get('password'));if(password!==String(f.get('password2')))return msg.innerHTML='<div class="danger-note">兩次輸入的密碼不一致。</div>';msg.innerHTML='<div class="note">正在建立帳號並套用專案權限…</div>';const r=await fetch(`${U}/functions/v1/register-project-invitation`,{method:'POST',headers:{'Content-Type':'application/json',apikey:K},body:JSON.stringify({token:t,email,password,name:String(f.get('name')).trim()})});const o=await r.json().catch(()=>({}));if(!r.ok){msg.innerHTML=`<div class="danger-note">${esc(o.error||'建立帳號失敗')}</div>`;return}const {error}=await sb.auth.signInWithPassword({email,password});if(error){msg.innerHTML='<div class="note">帳號已建立完成。請返回登入頁，以剛設定的密碼登入。</div>';return}showLoading();location.href=dash(o.project_id)};}
 function setup(){html('<div class="badge">平台已啟用</div><h1>首次總管理員已完成</h1><p class="muted">此平台已建立總管理員。請返回登入。</p><button id="back" class="btn primary" style="width:100%">返回登入</button>');document.getElementById('back').onclick=()=>login()}
 async function start(){showLoading();if(!(await loadSDK()))return html('<h1>系統元件載入失敗</h1><p class="muted">請確認網路後重新載入。</p><button onclick="location.reload()" class="btn primary" style="width:100%">重新載入</button>');sb=window.supabase.createClient(U,K,{auth:{persistSession:true,storage:sessionStorage,autoRefreshToken:true,detectSessionInUrl:true}});const {data:{session}}=await sb.auth.getSession();const t=invite();if(session&&t){try{const pid=await accept(t);return location.href=dash(pid)}catch(e){return login(e.message)}}if(session)return location.href=dash();login()}
 start();
})();