'use strict';
(function(){
 const U='https://ppdrsoltvqiqnbnlimbb.supabase.co',K='sb_publishable_Ev2C5000djbQq4wLDUKh9A_oF3H3WBd',V='20260910o',app=document.getElementById('app');let sb;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const invite=()=>new URLSearchParams(location.search).get('invite')||'';
 const roleName=r=>({judge:'評審',staff:'工作人員',project_admin:'專案管理員'}[r]||r||'受邀成員');
 const taskSummary=meta=>{const a=Array.isArray(meta.assignment_config)?meta.assignment_config:[];if(meta.role!=='judge'||!a.length)return'';return a.map(x=>{const rounds=[];if(x.round1_enabled)rounds.push('第一輪入圍初選');if(x.round2_enabled)rounds.push('第二輪正式評分');return`${x.group_name}：${rounds.join('＋')}`}).join('、')};
 const html=b=>app.innerHTML=`<main class="login"><div class="login-card">${b}</div></main>`;
 const showLoading=()=>app.innerHTML='<div class="loader-screen" role="status" aria-live="polite"><div class="loader-center"><div class="loader-book" aria-hidden="true">📖</div><div class="loader-dots" aria-hidden="true"><i></i><i></i><i></i></div><span class="sr-only">載入中</span></div></div>';
 const dash=pid=>`./dashboard.html?v=${V}${pid?`#project/${encodeURIComponent(pid)}`:''}`;
 const clearInvite=()=>history.replaceState({},'',location.pathname);
 async function loadSDK(){if(window.supabase?.createClient)return true;for(const src of ['https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.115.0/dist/umd/supabase.min.js','https://unpkg.com/@supabase/supabase-js@2.115.0/dist/umd/supabase.js']){try{await new Promise((ok,no)=>{const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=no;document.head.appendChild(s)});if(window.supabase?.createClient)return true}catch{}}return false}
 async function previewInvite(token){const {data,error}=await sb.rpc('get_project_invitation_preview',{p_token:token});if(error)throw error;const x=Array.isArray(data)?data[0]:data;if(!x)throw new Error('邀請連結無效、已使用、已撤銷或已過期');return x}
 async function accept(token){const {data:{session}}=await sb.auth.getSession();if(!session)throw new Error('尚未登入');const r=await fetch(`${U}/functions/v1/accept-project-invitation`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`,apikey:K},body:JSON.stringify({token})});const o=await r.json().catch(()=>({}));if(!r.ok)throw new Error(o.error||'接受邀請失敗');return o.project_id}
 function login(msg='',opts={}){
  const t=opts.token||'';const email=String(opts.email||'');const lock=!!opts.lockEmail;const invited=!!(t||opts.projectId);const good=!!opts.success;
  html(`<div class="badge">${invited?'專案邀請':'受保護正式系統'}</div><h1>${invited?'登入競賽專案':'競賽專案評審管理平台'}</h1><p class="muted">${invited?'帳號已準備完成，請使用受邀 Email 與密碼登入。':'僅限經授權的管理員、工作人員與評審登入。'}</p>${msg?`<div class="${good?'note':'danger-note'}">${esc(msg)}</div>`:''}<form id="login"><label class="label">電子郵件</label><input class="input" name="email" type="email" autocomplete="username" value="${esc(email)}" ${lock?'readonly aria-readonly="true"':''} required><label class="label">密碼</label><input class="input" name="password" type="password" autocomplete="current-password" required autofocus><button class="btn primary" style="width:100%;margin-top:15px">登入</button></form>${!invited?'<button id="setup" class="btn" style="width:100%;margin-top:10px">首次初始化總管理員</button>':''}`);
  document.getElementById('login').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),mail=String(f.get('email')).trim().toLowerCase(),password=String(f.get('password'));const {error}=await sb.auth.signInWithPassword({email:mail,password});if(error)return login('登入失敗，請確認密碼是否正確。',{...opts,email:mail});showLoading();try{let pid=opts.projectId||'';if(t){pid=await accept(t);clearInvite()}location.href=dash(pid)}catch(err){login(err.message,{...opts,email:mail})}};
  if(!invited)document.getElementById('setup').onclick=()=>setup();
 }
 function register(t,meta){
  const tasks=taskSummary(meta);
  html(`<div class="badge">專案邀請</div><h1>設定你的帳號</h1><p class="muted">你已受邀加入「${esc(meta.project_name)}」擔任${esc(roleName(meta.role))}。Email 已由管理員指定，你只需要填寫姓名並設定密碼。</p>${tasks?`<div class="note"><b>你的評審任務</b><br>${esc(tasks)}</div>`:''}<form id="reg"><label class="label">受邀電子郵件</label><input class="input" name="email" type="email" value="${esc(meta.email)}" readonly aria-readonly="true"><label class="label">姓名</label><input class="input" name="name" autocomplete="name" required autofocus><label class="label">設定密碼</label><input class="input" name="password" type="password" minlength="12" maxlength="128" required autocomplete="new-password"><label class="label">再次輸入密碼</label><input class="input" name="password2" type="password" minlength="12" maxlength="128" required autocomplete="new-password"><p class="muted tiny">密碼至少 12 個字元。管理員不會看到你的密碼。</p><button class="btn primary" style="width:100%;margin-top:15px">建立帳號</button></form><div id="msg"></div><button id="existing" class="btn" style="width:100%;margin-top:10px">我已經有這個帳號，改用登入</button>`);
  document.getElementById('existing').onclick=()=>login('',{email:meta.email,token:t,lockEmail:true});
  document.getElementById('reg').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),msg=document.getElementById('msg'),email=String(meta.email).trim().toLowerCase(),password=String(f.get('password')),name=String(f.get('name')).trim();if(!name)return msg.innerHTML='<div class="danger-note">請填寫姓名。</div>';if(password!==String(f.get('password2')))return msg.innerHTML='<div class="danger-note">兩次輸入的密碼不一致。</div>';msg.innerHTML='<div class="note">正在建立帳號並套用專案權限…</div>';const r=await fetch(`${U}/functions/v1/register-project-invitation`,{method:'POST',headers:{'Content-Type':'application/json',apikey:K},body:JSON.stringify({token:t,email,password,name})});const o=await r.json().catch(()=>({}));if(!r.ok){msg.innerHTML=`<div class="danger-note">${esc(o.error||'建立帳號失敗')}</div>`;return}clearInvite();login('帳號設定完成。請輸入剛才設定的密碼登入。',{email,projectId:o.project_id,lockEmail:true,success:true})};
 }
 function invalidInvite(message){clearInvite();html(`<div class="badge">專案邀請</div><h1>邀請連結無法使用</h1><div class="danger-note">${esc(message||'邀請連結無效、已使用、已撤銷或已過期')}</div><p class="muted">請聯絡專案管理員重新產生一次性邀請連結。</p><button id="normalLogin" class="btn" style="width:100%">返回一般登入</button>`);document.getElementById('normalLogin').onclick=()=>login()}
 function setup(){html('<div class="badge">平台已啟用</div><h1>首次總管理員已完成</h1><p class="muted">此平台已建立總管理員。請返回登入。</p><button id="back" class="btn primary" style="width:100%">返回登入</button>');document.getElementById('back').onclick=()=>login()}
 async function start(){
  showLoading();if(!(await loadSDK()))return html('<h1>系統元件載入失敗</h1><p class="muted">請確認網路後重新載入。</p><button onclick="location.reload()" class="btn primary" style="width:100%">重新載入</button>');
  sb=window.supabase.createClient(U,K,{auth:{persistSession:true,storage:sessionStorage,autoRefreshToken:true,detectSessionInUrl:true}});
  const t=invite();
  if(t){try{const meta=await previewInvite(t);const {data:{session}}=await sb.auth.getSession();if(session&&String(session.user?.email||'').toLowerCase()===String(meta.email||'').toLowerCase()){showLoading();const pid=await accept(t);clearInvite();return location.href=dash(pid)}if(session)await sb.auth.signOut();if(meta.account_exists)return login('這個 Email 已有平台帳號，請使用原本密碼登入並接受邀請。',{email:meta.email,token:t,lockEmail:true});return register(t,meta)}catch(e){return invalidInvite(e?.message||String(e))}}
  const {data:{session}}=await sb.auth.getSession();if(session)return location.href=dash();login();
 }
 start();
})();