'use strict';
(function(){
 const U='https://ppdrsoltvqiqnbnlimbb.supabase.co',K='sb_publishable_Ev2C5000djbQq4wLDUKh9A_oF3H3WBd';
 if(!window.supabase?.createClient)return;
 const sb=window.supabase.createClient(U,K,{auth:{persistSession:true,storage:sessionStorage,autoRefreshToken:true,detectSessionInUrl:true}});
 let profile=null;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function getProfile(){if(profile)return profile;const {data:{session}}=await sb.auth.getSession();if(!session)return null;const {data}=await sb.from('profiles').select('platform_role').eq('id',session.user.id).maybeSingle();profile=data;return profile}
 async function enhance(){const p=await getProfile();if(p?.platform_role!=='platform_admin')return;const cards=[...document.querySelectorAll('[data-project]')];cards.forEach(card=>{if(card.querySelector('[data-delete-project]'))return;const id=card.dataset.project,name=card.querySelector('h3')?.textContent.trim()||'';const wrap=document.createElement('div');wrap.style.cssText='margin-top:12px;display:flex;justify-content:flex-end';const b=document.createElement('button');b.className='btn danger';b.dataset.deleteProject=id;b.textContent='刪除專案';b.onclick=e=>{e.stopPropagation();openDelete(id,name)};wrap.appendChild(b);card.appendChild(wrap)});}
 function openDelete(id,name){document.body.insertAdjacentHTML('beforeend',`<div class="modal-back" id="deleteProjectModal"><div class="modal" style="max-width:620px"><div class="badge bad">危險操作</div><h2 style="margin-top:12px">永久刪除專案</h2><div class="danger-note"><b>此操作無法復原。</b><br>將永久刪除此專案及其作品、評分、成員、邀請、匯入紀錄與相關資料。</div><p>你準備刪除：</p><div class="card"><b>${esc(name)}</b></div><label class="label">請完整輸入專案名稱以確認</label><input class="input" id="deleteProjectName" autocomplete="off" placeholder="${esc(name)}"><label class="row" style="margin-top:14px;align-items:flex-start"><input type="checkbox" id="deleteProjectCheck" style="margin-top:4px"><span>我了解這是永久刪除，資料無法復原。</span></label><div class="row" style="justify-content:flex-end;margin-top:18px"><button class="btn" id="cancelDeleteProject">取消</button><button class="btn danger" id="confirmDeleteProject" disabled>永久刪除專案</button></div><div id="deleteProjectMsg"></div></div></div>`);
 const m=document.getElementById('deleteProjectModal'),input=document.getElementById('deleteProjectName'),check=document.getElementById('deleteProjectCheck'),go=document.getElementById('confirmDeleteProject'),msg=document.getElementById('deleteProjectMsg');
 const ready=()=>{go.disabled=!(input.value===name&&check.checked)};input.oninput=ready;check.onchange=ready;document.getElementById('cancelDeleteProject').onclick=()=>m.remove();
 go.onclick=async()=>{if(input.value!==name||!check.checked)return;const final=confirm(`最後確認：確定要永久刪除「${name}」？\n\n刪除後無法復原。`);if(!final)return;go.disabled=true;go.textContent='正在刪除…';const {error}=await sb.rpc('delete_project_permanently',{p_project:id,p_confirm_name:name});if(error){msg.innerHTML=`<div class="danger-note">${esc(error.message)}</div>`;go.disabled=false;go.textContent='永久刪除專案';return}m.remove();location.hash='';location.reload();};
 }
 const ob=new MutationObserver(()=>{clearTimeout(window.__pd);window.__pd=setTimeout(enhance,80)});ob.observe(document.body,{childList:true,subtree:true});setTimeout(enhance,250);
})();