'use strict';
(function(){
const U='https://ppdrsoltvqiqnbnlimbb.supabase.co',K='sb_publishable_Ev2C5000djbQq4wLDUKh9A_oF3H3WBd';
if(!window.supabase?.createClient)return;
const R=window.RF4={};
R.sb=window.supabase.createClient(U,K,{auth:{persistSession:true,storage:sessionStorage,autoRefreshToken:true,detectSessionInUrl:true}});
R.s={user:null,profile:null,project:null,role:null,group:'',token:0};R.pages={};
R.esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
R.fmt=d=>d?new Date(d).toLocaleString('zh-TW',{hour12:false}):'未設定';
R.localVal=d=>{if(!d)return'';const x=new Date(d),p=n=>String(n).padStart(2,'0');return`${x.getFullYear()}-${p(x.getMonth()+1)}-${p(x.getDate())}T${p(x.getHours())}:${p(x.getMinutes())}`};
R.iso=v=>v?new Date(v).toISOString():null;
R.roleName=r=>({platform_admin:'平台總管理員',project_admin:'專案管理員',staff:'工作人員',judge:'評審'}[r]||r||'—');
R.route=()=>{const p=(location.hash||'').replace(/^#/,'').split('/').filter(Boolean);if(p[0]!=='project'||!p[1])return null;let group='';try{group=p[3]?decodeURIComponent(p[3]):''}catch{group=p[3]||''}return{pid:p[1],page:p[2]||'overview',group}};
R.main=()=>document.querySelector('.main');R.isAdmin=()=>['platform_admin','project_admin'].includes(R.s.role);
R.badge=(t,c='')=>`<span class="badge ${c}">${R.esc(t)}</span>`;
R.toast=t=>{const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),3400)};
R.setMain=html=>{const m=R.main();if(!m)return false;m.innerHTML=html;m.dataset.reviewV4='1';document.documentElement.classList.remove('review-v4-pending');document.documentElement.classList.add('review-v4-ready');queueMicrotask(()=>window.RF4StableNav?.markActive?.());return true};
R.modal=html=>{document.getElementById('rf4modal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal-back" id="rf4modal"><div class="modal">${html}</div></div>`);return document.getElementById('rf4modal')};
R.closeModal=()=>document.getElementById('rf4modal')?.remove();
R.deadline=d=>{if(!d)return{label:'未設定',cls:''};const ms=new Date(d)-Date.now();return ms<0?{label:'已逾期',cls:'bad'}:ms<86400000?{label:'即將到期',cls:'warn'}:{label:'進行中',cls:'good'}};
R.context=async pid=>{const {data:{session}}=await R.sb.auth.getSession();if(!session)return false;R.s.user=session.user;const [{data:p},{data:pr}]=await Promise.all([R.sb.from('profiles').select('id,email,display_name,platform_role').eq('id',R.s.user.id).maybeSingle(),R.sb.from('projects').select('*').eq('id',pid).maybeSingle()]);if(!p||!pr)return false;R.s.profile=p;R.s.project=pr;if(p.platform_role==='platform_admin')R.s.role='platform_admin';else{const {data:m}=await R.sb.from('project_members').select('role,is_active').eq('project_id',pid).eq('user_id',R.s.user.id).maybeSingle();if(!m?.is_active)return false;R.s.role=m.role}return true};
R.assignments=async(uid=R.s.user?.id)=>{const {data}=await R.sb.from('judge_assignments').select('*').eq('project_id',R.s.project.id).eq('judge_user_id',uid);return data||[]};
R.syncNav=async()=>window.RF4StableNav?.sync?.();
R.requestReopen=async(group,round)=>{const reason=prompt('請簡要說明需要重新開放的原因（例如：誤按送出、希望微調）','');if(reason===null)return;const {error}=await R.sb.rpc('request_review_reopen',{p_project:R.s.project.id,p_group:group,p_round:round,p_reason:reason});if(error)return R.toast(error.message);R.toast('已送出重新開放申請')};
R.bindResolve=refresh=>document.querySelectorAll('[data-resolve]').forEach(b=>b.onclick=async()=>{const approve=b.dataset.ok==='1',note=prompt(approve?'核准備註（可留空）':'駁回原因（可留空）','');if(note===null)return;const {error}=await R.sb.rpc('resolve_review_reopen_request',{p_request:b.dataset.resolve,p_approve:approve,p_note:note});if(error)return R.toast(error.message);R.toast(approve?'已核准重新開放':'已駁回申請');refresh()});
R.render=async()=>{const r=R.route();if(!r||!R.pages[r.page])return;document.documentElement.classList.add('review-v4-pending');document.documentElement.classList.remove('review-v4-ready');const token=++R.s.token;try{if(!(await R.context(r.pid))||token!==R.s.token)return;if(r.group)R.s.group=r.group;await R.syncNav();if(token!==R.s.token)return;await R.pages[r.page]()}catch(e){console.error(e);R.setMain(`<section class="section"><div class="danger-note"><b>此頁載入失敗</b><br>${R.esc(e?.message||String(e))}</div><button class="btn" onclick="location.reload()">重新載入</button></section>`)}};
R.schedule=()=>{const r=R.route();if(!r||!R.pages[r.page]){document.documentElement.classList.remove('review-v4-pending');window.RF4StableNav?.markActive?.();return}document.documentElement.classList.add('review-v4-pending');const expected=`${r.pid}|${r.page}|${r.group||''}`;setTimeout(()=>{const q=R.route();if(q&&`${q.pid}|${q.page}|${q.group||''}`===expected)R.render()},120);setTimeout(()=>{const q=R.route(),m=R.main();if(q&&`${q.pid}|${q.page}|${q.group||''}`===expected&&m&&!m.dataset.reviewV4)R.render()},520)};
addEventListener('hashchange',R.schedule);setTimeout(R.schedule,260);
})();
