'use strict';
(function(){
const R=window.RF4;if(!R)return;const {sb,s}=R;
let W=null;
const maxScore=()=>Array.isArray(s.project?.scoring_rules)?s.project.scoring_rules.reduce((n,c)=>n+Number(c.max||0),0):0;
const expired=d=>!!d&&new Date(d).getTime()<Date.now();
function root(){let el=document.getElementById('rf4FastWorkspace');if(!el){el=document.createElement('div');el.id='rf4FastWorkspace';el.className='rf4-fast-workspace';document.body.appendChild(el)}return el}
function close(force=false){if(!W)return;const el=document.getElementById('rf4FastWorkspace');if(!force&&W.round===2&&W.dirty&&!confirm('目前這份評分有尚未儲存的修改，確定離開快速評分？'))return;el?.remove();document.body.classList.remove('rf4-fast-open');const cb=W.onClose;W=null;if(typeof cb==='function')cb()}
function current(){return W?.works?.[W.index]}
function assignment(){return W?.assignment||{}}
function statusText(){return `${W.group}｜${W.round===1?'第一輪入圍初選':'第二輪正式評分'}｜第 ${W.index+1}/${W.works.length} 份`}
function readingHtml(x){return `<div class="rf4-fast-meta"><span class="badge purple">${R.esc(W.group)}</span><span class="badge">${W.round===1?'第一輪｜入圍初選':'第二輪｜正式評分'}</span><span class="badge">${R.esc(x.category||'')}</span></div><h1 class="rf4-fast-title">${R.esc(x.title||'未命名作品')}</h1><div class="muted tiny">作品識別碼：${R.esc(x.anonymous_code||'')}　｜　文字字數 ${x.char_count??0}　｜　標點 ${x.punctuation_count??0}　｜　句號 ${x.period_count??0}</div>${x.warning_reason?`<div class="rf4-banner warn"><b>審查提示</b><br>${R.esc(x.warning_reason)}</div>`:''}<article class="rf4-fast-essay">${R.esc(x.safe_body||x.body||'')}</article>`}
function chrome(side){const x=current(),el=root();el.innerHTML=`<header class="rf4-fast-top"><div><div class="rf4-fast-kicker">快速評審工作區</div><b>${R.esc(statusText())}</b></div><div class="rf4-fast-top-actions"><span class="muted tiny">${R.esc(x?.anonymous_code||'')}</span><button class="btn" data-fast-prev ${W.index===0?'disabled':''}>←</button><button class="btn" data-fast-next ${W.index===W.works.length-1?'disabled':''}>→</button><button class="btn" id="rf4FastClose">離開</button></div></header><div class="rf4-fast-progress"><span style="width:${W.works.length?((W.index+1)/W.works.length*100).toFixed(2):0}%"></span></div><div class="rf4-fast-layout"><main class="rf4-fast-reading">${readingHtml(x)}</main><aside class="rf4-fast-side">${side}</aside></div>`;el.querySelector('#rf4FastClose').onclick=()=>close();document.body.classList.add('rf4-fast-open');el.scrollTop=0;return el}
async function move(delta){if(!W)return;if(W.round===2&&W.dirty){const ok=await saveRound2(false,false,true);if(!ok)return}const next=Math.max(0,Math.min(W.works.length-1,W.index+delta));if(next===W.index)return;W.index=next;if(W.round===1)await showRound1();else showRound2()}
function bindNav(el){el.querySelectorAll('[data-fast-prev]').forEach(b=>b.addEventListener('click',()=>move(-1)));el.querySelectorAll('[data-fast-next]').forEach(b=>b.addEventListener('click',()=>move(1)))}
async function ensureViewed(){const x=current();if(!x||W.submitted||expired(assignment().round1_deadline))return;const r=W.reviews.get(x.id);if(r?.viewed_at)return;const {error}=await sb.rpc('mark_round1_viewed',{p_project:s.project.id,p_submission:x.id});if(error){R.toast(error.message);return}W.reviews.set(x.id,{...(r||{}),submission_id:x.id,viewed_at:new Date().toISOString(),selected:!!r?.selected})}
async function chooseRound1(selected,goNext){const x=current();if(!x||W.submitted||expired(assignment().round1_deadline))return;const r=W.reviews.get(x.id)||{};if(!!r.selected!==selected){const {error}=await sb.rpc('set_round1_selected',{p_project:s.project.id,p_submission:x.id,p_selected:selected});if(error)return R.toast(error.message);W.reviews.set(x.id,{...r,submission_id:x.id,viewed_at:r.viewed_at||new Date().toISOString(),selected})}if(goNext&&W.index<W.works.length-1){W.index++;await showRound1()}else await showRound1()}
async function submitRound1(){const viewed=W.works.filter(x=>W.reviews.get(x.id)?.viewed_at).length,selected=W.works.filter(x=>W.reviews.get(x.id)?.selected).length;if(viewed!==W.works.length)return R.toast('請先完成全部作品閱讀');if(!confirm(`確定正式送出 ${W.group} 第一輪結果？目前入選 ${selected} 份。送出後需由管理員重新開放才能修改。`))return;const {error}=await sb.rpc('submit_round1_group',{p_project:s.project.id,p_group:W.group});if(error)return R.toast(error.message);W.submitted=true;R.toast('第一輪結果已正式送出');await showRound1()}
async function showRound1(){await ensureViewed();const x=current(),r=W.reviews.get(x.id)||{},viewed=W.works.filter(i=>W.reviews.get(i.id)?.viewed_at).length,selected=W.works.filter(i=>W.reviews.get(i.id)?.selected).length,isExpired=expired(assignment().round1_deadline),locked=W.submitted||isExpired;const el=chrome(`<div class="rf4-fast-panel-head"><h2>快速入圍</h2><p class="muted">第一輪不打分數，只要判斷這篇是否值得入圍。</p></div><div class="grid cards rf4-fast-mini"><div class="card"><div class="muted">已閱讀</div><div class="metric">${viewed}/${W.works.length}</div></div><div class="card"><div class="muted">已入選</div><div class="metric">${selected}</div></div></div>${W.submitted?'<div class="rf4-banner good"><b>本組已正式送出。</b><br>現在只能查看；如需修改請申請管理員重新開放。</div>':isExpired?'<div class="rf4-banner bad">本組第一輪期限已截止，目前只能查看。</div>':'<div class="rf4-banner"><b>正式送出前都能調整。</b><br>按下入選或不入選會立即保存並可直接前往下一篇。</div>'}<div class="rf4-fast-choice ${r.selected?'selected':''}"><div class="muted">這篇目前狀態</div><strong>${r.selected?'✓ 已入選':'未入選'}</strong></div><div class="rf4-fast-big-actions">${locked?'':`<button class="btn" data-r1-no>不入選並下一篇</button><button class="btn primary" data-r1-yes>${r.selected?'維持入選並下一篇':'入選並下一篇'}</button>`}</div><div class="rf4-fast-nav"><button class="btn" data-fast-prev ${W.index===0?'disabled':''}>← 上一篇</button><button class="btn" data-fast-next ${W.index===W.works.length-1?'disabled':''}>下一篇 →</button></div>${!locked&&viewed===W.works.length?`<button class="btn good rf4-fast-submit" id="rf4FastSubmitR1">正式送出 ${R.esc(W.group)} 第一輪結果</button>`:''}<p class="muted tiny">快捷鍵：← / → 切換作品；I 入選並下一篇；N 不入選並下一篇。</p>`);bindNav(el);el.querySelector('[data-r1-no]')?.addEventListener('click',()=>chooseRound1(false,true));el.querySelector('[data-r1-yes]')?.addEventListener('click',()=>chooseRound1(true,true));el.querySelector('#rf4FastSubmitR1')?.addEventListener('click',submitRound1)}
function collectScore(form){const crit=Array.isArray(s.project.scoring_rules)?s.project.scoring_rules:[],values={};for(const c of crit){const v=Number(form.elements[c.code]?.value);if(!Number.isFinite(v))return null;values[c.code]=v}return values}
async function saveRound2(goNext=false,quiet=false,fromNav=false){const el=root(),form=el.querySelector('#rf4FastScore'),x=current();if(!form||W.submitted||expired(assignment().round2_deadline))return false;if(!form.reportValidity())return false;const values=collectScore(form);if(!values)return false;const comment=String(form.elements.comment?.value||'');const {error}=await sb.rpc('save_dynamic_score',{p_project:s.project.id,p_submission:x.id,p_values:values,p_comment:comment,p_lock:false});if(error){R.toast(error.message);return false}const total=Object.values(values).reduce((a,b)=>a+Number(b||0),0);W.scores.set(x.id,{...(W.scores.get(x.id)||{}),submission_id:x.id,score_values:values,total_score:total,comment,status:'draft'});W.dirty=false;if(!quiet)R.toast('已儲存');if(goNext&&W.index<W.works.length-1){W.index++;showRound2()}else if(!fromNav)showRound2();return true}
async function submitRound2(){const saved=W.works.filter(x=>W.scores.has(x.id)).length;if(saved!==W.works.length)return R.toast(`尚有 ${W.works.length-saved} 份未儲存`);if(W.dirty){const ok=await saveRound2(false,true);if(!ok)return}if(!confirm(`確定正式送出 ${W.group} 的全部第二輪評分？送出後需由管理員重新開放才能修改。`))return;const {error}=await sb.rpc('submit_round2_group',{p_project:s.project.id,p_group:W.group});if(error)return R.toast(error.message);W.submitted=true;R.toast('第二輪整組評分已正式送出');showRound2()}
function showRound2(){const x=current(),score=W.scores.get(x.id),crit=Array.isArray(s.project.scoring_rules)?s.project.scoring_rules:[],saved=W.works.filter(i=>W.scores.has(i.id)).length,isExpired=expired(assignment().round2_deadline),locked=W.submitted||isExpired;const fields=crit.map(c=>`<label class="rf4-fast-score-row"><span><b>${R.esc(c.label||c.code)}</b><small>滿分 ${Number(c.max||0)}</small></span><input class="input" name="${R.esc(c.code)}" type="number" min="0" max="${Number(c.max||0)}" step="0.5" value="${R.esc(score?.score_values?.[c.code]??'')}" ${locked?'disabled':''} required></label>`).join('');const el=chrome(`<div class="rf4-fast-panel-head"><h2>快速評分</h2><p class="muted">分數會先儲存為草稿，整組正式送出前都可再調整。</p></div><div class="grid cards rf4-fast-mini"><div class="card"><div class="muted">已儲存</div><div class="metric">${saved}/${W.works.length}</div></div><div class="card"><div class="muted">本篇總分</div><div class="metric" id="rf4FastTotal">${score?.total_score??0}</div><div class="muted tiny">滿分 ${maxScore()}</div></div></div>${W.submitted?'<div class="rf4-banner good">本組第二輪已正式送出，現在為唯讀。</div>':isExpired?'<div class="rf4-banner bad">第二輪期限已截止，請聯絡管理員延長。</div>':''}<form id="rf4FastScore">${fields}<label class="label">評語（選填）</label><textarea class="input" name="comment" rows="3" ${locked?'disabled':''}>${R.esc(score?.comment||'')}</textarea>${locked?'':`<div class="rf4-fast-big-actions"><button type="button" class="btn" id="rf4FastSave">儲存</button><button type="button" class="btn primary" id="rf4FastSaveNext">儲存並下一篇</button></div>`}</form><div class="rf4-fast-nav"><button class="btn" data-fast-prev ${W.index===0?'disabled':''}>← 上一篇</button><button class="btn" data-fast-next ${W.index===W.works.length-1?'disabled':''}>下一篇 →</button></div>${!locked&&saved===W.works.length?`<button class="btn good rf4-fast-submit" id="rf4FastSubmitR2">正式送出 ${R.esc(W.group)} 第二輪評分</button>`:''}<p class="muted tiny">快捷鍵：← / → 切換作品；Ctrl/⌘ + Enter 儲存並下一篇。</p>`);bindNav(el);const form=el.querySelector('#rf4FastScore');if(form&&!locked){const calc=()=>{let t=0;crit.forEach(c=>{const v=Number(form.elements[c.code]?.value);if(Number.isFinite(v))t+=v});el.querySelector('#rf4FastTotal').textContent=t};form.addEventListener('input',()=>{W.dirty=true;calc()});el.querySelector('#rf4FastSave')?.addEventListener('click',()=>saveRound2(false));el.querySelector('#rf4FastSaveNext')?.addEventListener('click',()=>saveRound2(true));}el.querySelector('#rf4FastSubmitR2')?.addEventListener('click',submitRound2)}
function keyHandler(e){if(!W)return;if(e.key==='Escape'){close();return}const tag=(document.activeElement?.tagName||'').toLowerCase(),typing=['input','textarea','select'].includes(tag);if(W.round===2&&typing){if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();saveRound2(true)}return}if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}else if(e.key==='ArrowRight'){e.preventDefault();move(1)}else if(W.round===1&&!typing&&(e.key==='i'||e.key==='I')){e.preventDefault();chooseRound1(true,true)}else if(W.round===1&&!typing&&(e.key==='n'||e.key==='N')){e.preventDefault();chooseRound1(false,true)}}
addEventListener('keydown',keyHandler);
R.openFastRound1=async function(opts={}){const {data:works,error}=await sb.rpc('get_judge_round_works',{p_project:s.project.id,p_round:1});if(error)return R.toast(error.message);const list=(works||[]).filter(x=>x.group_name===opts.group);if(!list.length)return R.toast('此組目前沒有可審查作品');const {data:revs}=await sb.from('round1_reviews').select('*').eq('project_id',s.project.id).eq('judge_user_id',s.user.id);const map=new Map((revs||[]).map(x=>[x.submission_id,x]));let idx=opts.startId?list.findIndex(x=>x.id===opts.startId):-1;if(idx<0)idx=list.findIndex(x=>!map.get(x.id)?.viewed_at);if(idx<0)idx=0;W={round:1,group:opts.group,works:list,index:idx,reviews:map,assignment:opts.assignment||{},submitted:!!opts.submitted,onClose:opts.onClose,dirty:false};await showRound1()};
R.openFastRound2=async function(opts={}){const {data:works,error}=await sb.rpc('get_judge_round_works',{p_project:s.project.id,p_round:2});if(error)return R.toast(error.message);const list=(works||[]).filter(x=>x.group_name===opts.group);if(!list.length)return R.toast('此組目前沒有第二輪作品');const {data:scores}=await sb.from('scores').select('*').eq('project_id',s.project.id).eq('judge_user_id',s.user.id);const map=new Map((scores||[]).map(x=>[x.submission_id,x]));let idx=opts.startId?list.findIndex(x=>x.id===opts.startId):-1;if(idx<0)idx=list.findIndex(x=>!map.has(x.id));if(idx<0)idx=0;W={round:2,group:opts.group,works:list,index:idx,scores:map,assignment:opts.assignment||{},submitted:!!opts.submitted,onClose:opts.onClose,dirty:false};showRound2()};
R.closeFastWorkspace=close;
const priorSetMain=R.setMain;
R.setMain=html=>{
 const r=R.route();
 if(r?.page==='round1'&&html.includes('<h2>第一輪審查</h2>')){
  html=html.replace('<h2>第一輪審查</h2>',`<div class="rf4-quick-entry"><div><h2>第一輪審查</h2><p class="muted">大量作品建議直接使用快速審查：閱讀、入選／不入選、下一篇都在同一畫面完成。</p></div><button class="btn primary" data-fast-start="1">開始／繼續快速審查</button></div>`).replace(/>閱讀<\/button>/g,'>快速審查</button>');
 }
 if(r?.page==='round2'&&html.includes('<h2>第二輪評分</h2>')){
  html=html.replace('<h2>第二輪評分</h2>',`<div class="rf4-quick-entry"><div><h2>第二輪評分</h2><p class="muted">快速評分會把正文、評分欄位、儲存與上一篇／下一篇放在同一工作區。</p></div><button class="btn primary" data-fast-start="2">開始／繼續快速評分</button></div>`).replace(/>評分／調整<\/button>/g,'>快速評分／調整</button>');
 }
 html=html.replace(/>進入第一輪<\/button>/g,'>開始快速審查</button>').replace(/>進入第二輪<\/button>/g,'>開始快速評分</button>');
 const out=priorSetMain(html);setTimeout(()=>autoStartIfNeeded(),0);return out;
};
async function openFromPage(round,startId=''){const field=round===1?'round1_enabled':'round2_enabled';const {data:as,error}=await sb.from('judge_assignments').select('*').eq('project_id',s.project.id).eq('judge_user_id',s.user.id).eq(field,true);if(error)return R.toast(error.message);if(!as?.length)return R.toast(round===1?'你目前沒有第一輪審查權限':'你目前沒有第二輪評分權限');let group=s.group;if(!as.some(a=>a.group_name===group))group=as[0].group_name;s.group=group;const a=as.find(x=>x.group_name===group);if(round===1){const {data:sent}=await sb.from('round1_judge_submissions').select('group_name').eq('project_id',s.project.id).eq('judge_user_id',s.user.id).eq('group_name',group);return R.openFastRound1({group,assignment:a,submitted:!!sent?.length,startId,onClose:()=>R.pages.round1()})}const {data:sent}=await sb.from('round2_judge_submissions').select('group_name').eq('project_id',s.project.id).eq('judge_user_id',s.user.id).eq('group_name',group);return R.openFastRound2({group,assignment:a,submitted:!!sent?.length,startId,onClose:()=>R.pages.round2()})}
async function autoStartIfNeeded(){const r=R.route();if(!r||!['round1','round2'].includes(r.page)||document.getElementById('rf4FastWorkspace'))return;let q=null;try{q=JSON.parse(sessionStorage.getItem('rf4_quick_start')||'null')}catch{}if(!q||q.pid!==r.pid||q.page!==r.page)return;sessionStorage.removeItem('rf4_quick_start');if(q.group)s.group=q.group;await openFromPage(r.page==='round1'?1:2)}
document.addEventListener('click',e=>{const task=e.target.closest?.('[data-task]');if(task&&['round1','round2'].includes(task.dataset.task)){const r=R.route();if(r)sessionStorage.setItem('rf4_quick_start',JSON.stringify({pid:r.pid,page:task.dataset.task,group:task.dataset.group||''}))}const start=e.target.closest?.('[data-fast-start]');if(start){e.preventDefault();e.stopImmediatePropagation();openFromPage(Number(start.dataset.fastStart));return}const read=e.target.closest?.('[data-read]');if(read&&R.route()?.page==='round1'){e.preventDefault();e.stopImmediatePropagation();openFromPage(1,read.dataset.read);return}const score=e.target.closest?.('[data-score]');if(score&&R.route()?.page==='round2'){e.preventDefault();e.stopImmediatePropagation();openFromPage(2,score.dataset.score);return}},true);
})();
